import { values } from "lodash";

export const MLAdvancedSettingsFields = {
  cluster_abc_xyz: {
    question: "Cluster using ABC-XYZ classification?",
    path: "feature_engg.cluster_abc_xyz",
    direction: "column",
    type: "Check",
    target: "config",
    xs: 4,
    md: 4,
  },
  time_seasonality: {
    question: "Turn On time-based seasonality?",
    path: "feature_engg.time_seasonality",
    direction: "column",
    type: "Check",
    target: "config",
    xs: 4,
    md: 4,
  },
  time_to_event: {
    question: "Turn on time to event features?",
    path: "feature_engg.time_to_event",
    direction: "column",
    target: "config",
    type: "Check",
    xs: 4,
    md: 4,
  },
  new_product_forecasting: {
    question: "Need new product forecasting?",
    path: "stacking.NewProduct",
    direction: "column",
    type: "Check",
    xs: 4,
    md: 4,
  },
  metrics_clusterA: {
    question: "Metrics only for ClusterA?",
    path: "scenario_plan.clusterA",
    direction: "column",
    type: "Check",
    target: "config",
    xs: 8,
    md: 8,
  },
  groups_selection: {
    label: "Select Groups For Data Segmentation",
    isMultiSelect: true,
    type: "AutoComplete",
    target: "config",
    placeholder: "Select Groups...",
    path: "feature_engg.groups[0].group_id_columns",
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Group 1", "Group 2", "Group 3", "Group 4"],
  },
  models_selection: {
    label: "Select Models For Run",
    isMultiSelect: true,
    type: "AutoComplete",
    placeholder: "Select Models...",
    target: "config",
    path: "training.groups.cluster.model_names",
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },
  feature_types: {
    label: "Select Feature Types to be created",
    isMultiSelect: true,
    type: "AutoComplete",
    path: "feature_engg.feature_types",
    showLabel: true,
    xs: 12,
    md: 12,
    values: [
      "regressor",
      "target_encoded",
      "label_encoded",
      "text_encoded",
      "holiday",
      "holiday_US",
      "holiday_CA",
      "datetime",
      "sinusoidal",
      "offset",
      "lagged",
      "driver",
      "exogenous_features",
    ],
  },
  oscillator_features: {
    label: "Oscillator Features",
    isMultiSelect: true,
    type: "AutoComplete",
    path: "scenario_plan.oscillator_features",
    showLabel: true,
    xs: 12,
    md: 12,
    values: [
      "regressor",
      "target_encoded",
      "label_encoded",
      "text_encoded",
      "holiday",
      "holiday_US",
      "holiday_CA",
      "datetime",
      "sinusoidal",
      "offset",
      "lagged",
      "driver",
      "exogenous_features",
    ],
  },
  driver_offset_columns: {
    label: "Driver Offset columns",
    isMultiSelect: true,
    type: "AutoComplete",
    target: "config",
    path: "feature_engg.driver_offset_cols",
    showLabel: true,
    xs: 12,
    md: 12,
    values: [
      "regressor",
      "target_encoded",
      "label_encoded",
      "text_encoded",
      "holiday",
      "holiday_US",
      "holiday_CA",
      "datetime",
      "sinusoidal",
      "offset",
      "lagged",
      "driver",
      "exogenous_features",
    ],
  },
  offset_create_gap: {
    question: "Create gap",
    path: "feature_engg.offset_params.create_gap",
    direction: "column",
    type: "Check",
    target: "config",
    xs: 3,
    md: 3,
  },
  period_types: {
    label: "Select Period for Creating Offsets",
    isMultiSelect: true,
    type: "AutoComplete",
    path: "feature_engg.offset_params.period_types",
    target: "config",
    showLabel: true,
    xs: 9,
    md: 9,
    values: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
  },
  lag_create_gap: {
    question: "Create gap",
    path: "feature_engg.lag_params.create_gap",
    direction: "column",
    type: "Check",
    target: "config",
    xs: 3,
    md: 3,
  },
  min_lag: {
    label: "Min lag",
    isMultiSelect: false,
    type: "AutoComplete",
    path: "feature_engg.lag_params.range[0]",
    showLabel: true,
    xs: 2,
    md: 2,
    target: "config",
    values: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
  },
  max_lag: {
    label: "Max lag",
    isMultiSelect: false,
    type: "AutoComplete",
    path: "feature_engg.lag_params.range[1]",
    showLabel: true,
    xs: 2,
    md: 2,
    target: "config",
    values: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
  },
  lag_step: {
    label: "Lag step",
    isMultiSelect: false,
    type: "AutoComplete",
    path: "feature_engg.lag_params.range[2]",
    showLabel: true,
    xs: 2,
    md: 2,
    target: "config",
    values: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
  },
  customer_tag_values: {
    label: "Customer tag values",
    isMultiSelect: true,
    type: "AutoComplete",
    path: "feature_engg.lag_params.values",
    showLabel: true,
    xs: 3,
    md: 3,
    target: "config",
    values: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
  },

  time_interaction_dimensions: {
    label: "Select Time Interaction Dimensions",
    isMultiSelect: true,
    type: "AutoComplete",
    path: "feature_engg.time_interaction_dimensions",
    showLabel: true,
    xs: 12,
    md: 12,
    target: "config",
    values: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
  },

  candidates: {
    label: "Select no. of candidates for stacking",
    type: "Counter",
    target: "config",
    path: "stacking.n_candidates",
    showLabel: true,
    xs: 6,
    md: 6,
    maxRange: 10,
    minRange: 0,
  },
  k_best_candidates: {
    label: "Select k best candidates for stacking",
    type: "Counter",
    path: "stacking.k_best_candidates",
    showLabel: true,
    xs: 6,
    md: 6,
    target: "config",
    maxRange: 5000,
    minRange: 0,
  },
  enrichment_percentage: {
    label: "Select Percentage for planner enrichment",
    type: "Counter",
    path: "stacking.enrichment",
    showLabel: true,
    xs: 6,
    md: 6,
    target: "config",

    maxRange: 100,
    minRange: 0,
  },
  multiprocessing_threshold: {
    label: "Multiprocessing Threshold",
    type: "Counter",
    path: "feature_engg.multiprocessing_threshold",
    showLabel: true,
    xs: 6,
    md: 6,
    target: "config",
    maxRange: 5000,
    minRange: 0,
  },

  


  // Planner Adjustments

  exogenous_feature_name: {
    label: "Exogenous Feature Name",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select feature",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 12,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },
  dimension: {
    label: "Select Dimension",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select dimension",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },
  value: {
    label: "Select Value",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select value",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },

  adjustments_start_date: {
    component: "DatePicker",
    target: "config",
    label: "Adjustment Start Date",
    path: null,
    showLabel: true,
    required: false,
    xs: 12,
    md: 6,
  },
  adjustments_end_date: {
    component: "DatePicker",
    target: "config",
    label: "Adjustment End Date",
    path: null,
    showLabel: true,
    required: false,
    xs: 12,
    md: 6,
  },

  operation_type: {
    label: "Operation Type",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select type",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },

  adjustment_value: {
    component: "Counter",
    target: "config",
    showLabel: true,
    placeholder: "Set adjustment value",
    label: "Adjustment Value",
    maxRange: 5000,
    minRange: 0,
    path: null,
    xs: 12,
    md: 6,
  },

  // Exogenous Features

  operation_type: {
    label: "Operation Type",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select type",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },

  enrichment_start_date: {
    component: "DatePicker",
    target: "config",
    label: "Enrichment Start Date",
    path: null,
    showLabel: true,
    required: false,
    xs: 12,
    md: 6,
  },
  enrichment_end_date: {
    component: "DatePicker",
    target: "config",
    label: "Enrichment End Date",
    path: null,
    showLabel: true,
    required: false,
    xs: 12,
    md: 6,
  },

  //Add Planner Enrichments

  exogenous_feature_name: {
    label: "Exogenous Feature Name",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select feature",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 12,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },
  dimension: {
    label: "Select Dimension",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select dimension",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },
  value: {
    label: "Select Value",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select value",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },

  enrichment_start_date: {
    component: "DatePicker",
    target: "config",
    label: "Enrichment Start Date",
    path: null,
    showLabel: true,
    required: false,
    xs: 12,
    md: 6,
  },
  enrichment_end_date: {
    component: "DatePicker",
    target: "config",
    label: "Enrichment End Date",
    path: null,
    showLabel: true,
    required: false,
    xs: 12,
    md: 6,
  },

  operation_type: {
    label: "Operation Type",
    isMultiSelect: false,
    type: "AutoComplete",
    placeholder: "Select type",
    target: "config",
    path: null,
    showLabel: true,
    xs: 12,
    md: 6,
    values: ["Xgboost", "MLP", "LSTM", "Xgblinear", "GRU"],
  },

  enrichment_value: {
    component: "Counter",
    target: "config",
    showLabel: true,
    placeholder: "Set adjustment value",
    label: "Adjustment Value",
    maxRange: 5000,
    minRange: 0,
    path: null,
    xs: 12,
    md: 6,
  },
};
