export const mlAdvancedSettingsFields = (
  dimensionOptions,
  modelsArray,
  featuresArray,
  clustersArray,
  numericArray,
  driverColumns,
  kBestCandidatesMaxRange,
  kBestCandidatesMinRange,
  candidatesMaxRange,
  candidatesMinRange,
  percentageMaxRange,
  percentageMinRange,
  taggedColumns,
  ts_id_columns,
  config
) => {
  return {
    // Forecasting Settings
    cluster_abc_xyz: {
      label: "Cluster using ABC-XYZ classification?",
      type: "Check",
      target: "config",
      path: "feature_engg.cluster_abc_xyz",
      direction: "column",
      xs: 12,
      md: 2.75,
    },
    time_seasonality: {
      label: "Turn On time-based seasonality?",
      type: "Check",
      target: "config",
      path: "feature_engg.time_seasonality",
      direction: "column",
      xs: 12,
      md: 2.5,
    },
    time_to_event: {
      label: "Turn on time to event features?",
      type: "Check",
      target: "config",
      path: "feature_engg.time_to_event",
      direction: "column",
      xs: 12,
      md: 2.5,
    },
    clusterA: {
      label: "Hide Train Data?",
      type: "Check",
      target: "config",
      path: "scenario_plan.clusterA",
      direction: "column",
      xs: 12,
      md: 2.125,
    },
    exclude_granular_forecast: {
      label: "Disable Granular Filters?",
      type: "Check",
      target: "config",
      path: "scenario_plan.exclude_granular_forecast",
      direction: "column",
      xs: 12,
      md: 2.125,
    },
    // Model Selection
    groups_selection: {
      label: "Select Groups For Data Segmentation",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select",
      path: "feature_engg.groups[0].group_id_columns",
      showLabel: true,
      xs: 12,
      md: 4,
      values: "dimensionOptions",
    },
    models_selection: {
      label: "Select Models For Run",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select",
      path: "training.groups.cluster.model_names",
      showLabel: true,
      xs: 12,
      md: 5,
      values: modelsArray,
    },

    train_metrics_weight: {
      label: "Train Metrics Weight",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "training.train_metrics_weight",
      showLabel: true,
      maxRange: 1,
      minRange: 0,
      xs: 12,
      md: 3,
    },

    // Model Feature Settings
    feature_types: {
      label: "Select Feature Types to be created",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "feature_engg.feature_types",
      showLabel: true,
      xs: 12,
      md: 12,
      values: featuresArray,
    },

    oscillator_features: {
      label: "Oscillator Features",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "scenario_plan.oscillator_features",
      showLabel: true,
      xs: 12,
      md: 12,
      values: featuresArray,
    },

    // Offset Parameters
    create_gap_offset: {
      label: "Create gap",
      type: "Check",
      target: "config",
      path: "feature_engg.offset_params.create_gap",
      direction: "column",
      xs: 12,
      md: 2,
    },

    driver_offset_cols: {
      label: "Driver Offset columns",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder:
        "Select the drivers whose offset should be created (used only when offset is selected in Feature Types)",
      path: "feature_engg.driver_offset_cols",
      showLabel: true,
      xs: 12,
      md: 3,
      values: driverColumns,
    },

    offset_period_types: {
      label: "Select Period for Creating Offsets",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Choose an option",
      path: "feature_engg.offset_params.period_types",
      showLabel: true,
      xs: 12,
      md: 4,
      values: numericArray,
    },

    function_types: {
      label: "Select Function Types for Creating Offsets",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Choose an option",
      path: "feature_engg.offset_params.function_types",
      showLabel: true,
      xs: 12,
      md: 3,
      values: ["mean", "linear_regression"],
    },

    // Lag Parameters
    create_gap_lag: {
      label: "Create gap",
      type: "Check",
      target: "config",
      path: "feature_engg.lag_params.create_gap",
      direction: "column",
      xs: 12,
      md: 3,
    },
    min_lag: {
      label: "Min lag",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select",
      path: "feature_engg.lag_params.range[0]",
      showLabel: true,
      xs: 12,
      md: 2,
      values: numericArray,
    },
    max_lag: {
      label: "Max lag",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select",
      path: "feature_engg.lag_params.range[1]",
      showLabel: true,
      xs: 12,
      md: 2,
      values: numericArray,
    },
    lag_step: {
      label: "Lag step",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select",
      path: "feature_engg.lag_params.range[2]",
      showLabel: true,
      xs: 12,
      md: 2,
      values: numericArray,
    },
    customer_tag_values: {
      label: "Custom lag values",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select",
      path: "feature_engg.lag_params.values",
      showLabel: true,
      xs: 12,
      md: 3,
      values: numericArray,
    },

    // Time Interaction
    time_interaction_dimensions: {
      label: "Select Time Interaction Dimensions",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select time interaction dimensions",
      path: "feature_engg.time_interaction_dimensions",
      showLabel: true,
      xs: 12,
      md: 12,
      values: "dimensionOptions",
    },

    // Miscellaneous Settings
    use_candidate_weight: {
      label: "Use Candidate Weight?",
      type: "Check",
      target: "config",
      path: "stacking.candidate_weight",
      direction: "column",
      xs: 12,
      md: 2,
    },

    include_train_metrics: {
      label: "Include Train Metric",
      type: "Check",
      target: "config",
      path: "stacking.include_train_metrics",
      direction: "column",
      xs: 12,
      md: 2,
    },
    n_candidates: {
      label: "Select no. of candidates for stacking",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "stacking.n_candidates",
      showLabel: true,
      maxRange: candidatesMaxRange,
      minRange: candidatesMinRange,
      xs: 12,
      md: 4,
    },
    k_best_candidates: {
      label: "Select k best candidates for stacking",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "stacking.k_best_candidates",
      showLabel: true,
      maxRange: kBestCandidatesMaxRange,
      minRange: kBestCandidatesMinRange,
      xs: 12,
      md: 4,
    },
    enrichment_percentage: {
      label: "Select Percentage for planner enrichment",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "stacking.enrichment",
      showLabel: true,
      maxRange: percentageMaxRange,
      minRange: percentageMinRange,
      xs: 12,
      md: 6,
    },
    multiprocessing_threshold: {
      label: "Multiprocessing Threshold",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "feature_engg.multiprocessing_threshold",
      showLabel: true,
      maxRange: 5000,
      minRange: percentageMinRange,
      xs: 12,
      md: 6,
    },

    rl_agents: {
      label: "Enable RL Agent",
      type: "Check",
      target: "config",
      path: "stacking.rl_agents",
      direction: "row",
      xs: 12,
      md: 12,
    },

    forecast_type_for_reward: {
      label: "Select Forecast Type for Reward",
      isMultiSelect: false,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select forecast type for reward",
      path: "agent_settings.forecast_type_for_reward",
      showLabel: true,
      xs: 12,
      md: 6,
      values: ["ML Forecast", "Locked Forecast", "Consensus Forecast"],
    },
    experiments_history_exp_path: {
      label: "Select Experiment",
      type: "AutoComplete",
      target: "experiments_history",
      isMultiSelect: false,
      placeholder: "Select experiment",
      path: "exp_path",
      showLabel: true,
      xs: 12,
      md: 12,
      values: "experiments_list",
    },
    experiments_history_date_tag: {
      label: "Select Date Tag",
      type: "AutoComplete",
      target: "experiments_history",
      placeholder: "Select date tag",
      path: "date_tag",
      showLabel: true,
      values: "date_columns",
      isMultiSelect: false,
      target_file: "scenario_planning/K_best/forecast/final_da_data_backup.csv",
      xs: 12,
      md: 12,
    },

    forecast_deviation: {
      label: "Deviation Lag",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "agent_settings.forecast_deviation",
      showLabel: true,
      minRange: 1,
      maxRange: 52,
      xs: 12,
      md: 6,
    },
    accuracy_by_test_horizon: {
      label: "Accuracy by Test Horizon?",
      type: "Check",
      target: "config",
      path: "agent_settings.accuracy_by_test_horizon",
      direction: "column",
      xs: 12,
      md: 6,
    },
    test_horizon: {
      label: "Test Horizon",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "agent_settings.test_horizon",
      showLabel: true,
      minRange: 1,
      maxRange: 30,
      xs: 12,
      md: 6,
    },

    accuracy_by_n_horizon: {
      label: "Accuracy by n Horizon?",
      type: "Check",
      target: "config",
      path: "agent_settings.accuracy_by_n_horizon",
      direction: "column",
      xs: 12,
      md: 6,
    },

    past_accuracy_horizon: {
      label: "Past n Horizon",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "agent_settings.past_accuracy_horizon",
      showLabel: true,
      minRange: 1,
      maxRange: 30,
      xs: 12,
      md: 6,
    },

    enable_rl_agent_forecast: {
      label: "Accept Agent Recommendations",
      type: "Check",
      target: "config",
      path: "agent_settings.enable_rl_agent_forecast",
      direction: "row",
      xs: 12,
      md: 12,
    },

    rl_agent_forecast_granularity: {
      label: "Enrichment Granularity",
      isMultiSelect: false,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select Enrichment Granularity",
      path: "agent_settings.rl_agent_forecast_granularity",
      showLabel: true,
      xs: 12,
      md: 12,
      values: ts_id_columns,
    },

    rl_agent_forecast_eligible_actions: {
      label: "Eligible Actions",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Eligible Actions",
      path: "agent_settings.rl_agent_forecast_eligible_actions",
      showLabel: true,
      xs: 12,
      md: 12,
      values: [
        "upper_bound",
        "lower_bound",
        "offset",
        "P10",
        "P20",
        "P30",
        "P40",
        "P50",
        "P60",
        "P70",
        "P80",
        "P90",
        "P99",
        "ml_forecast",
      ],
    },

    rl_agent_start_date: {
      label: "Start Date",
      type: "DatePicker",
      target: "config",
      path: "agent_settings.rl_agent_forecast_start_date",
      showLabel: true,
      xs: 12,
      md: 6,
    },

    rl_agent_end_date: {
      label: "End Date",
      type: "DatePicker",
      target: "config",
      path: "agent_settings.rl_agent_forecast_end_date",
      showLabel: true,
      xs: 12,
      md: 6,
    },

    // New Product Settings
    need_new_product_forecasting: {
      label: "Need new product forecasting?",
      type: "Check",
      target: "config",
      path: "stacking.NewProduct",
      direction: "column",
      xs: 12,
      md: 3,
    },
    // new_product_days_cutoff: {
    //   label: "New Product Days Cutoff",
    //   type: "Counter",
    //   target: "config",
    //   placeholder: "Set your count",
    //   path: "stacking.NewProduct_DaysCutoff",
    //   showLabel: true,
    //   maxRange: 5000,
    //   minRange: 0,
    //   xs: 12,
    //   md: 4.5,
    // },
    new_product_sale_days: {
      label: "New Product Sale Days",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "stacking.NewProduct_SaleDays",
      showLabel: true,
      maxRange: 5000,
      minRange: 0,
      xs: 12,
      md: 4.5,
    },

    // Out Of Stock Settings
     impute_irregular_spikes: {
      label: "Impute Irregular Spikes?",
      type: "Check",
      target: "config",
      path: "feature_engg.impute_irregular_spikes",
      direction: "column",
      xs: 12,
      md: 2,
    },
     spike_clusters: {
      label: "Spike Clusters",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Spike Clusters",
      path: "feature_engg.spike_clusters",
      showLabel: true,
      xs: 12,
      md: 3,
      values: clustersArray,
    },
    impute_out_of_stock: {
      label: "Impute Out Of Stock?",
      type: "Check",
      target: "config",
      path: "feature_engg.impute_outofstock",
      direction: "column",
      xs: 12,
      md: 2,
    },
    out_of_stock_clusters: {
      label: "Select Out Of Stock Clusters",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select out of stock clusters",
      path: "feature_engg.oos_clusters",
      showLabel: true,
      xs: 12,
      md: 3,
      values: clustersArray,
    },
    rate_of_decline: {
      label: "Rate Of Decline",
      type: "Counter",
      target: "config",
      placeholder: "Set rate of decline",
      path: "feature_engg.rate_of_decline",
      showLabel: true,
      maxRange: 10,
      minRange: -10,
      xs: 12,
      md: 2,
    },

    compute_mutual_info: {
      label: "Compute Mutual Information",
      type: "Check",
      target: "config",
      path: "feature_engg.mutual_info.compute",
      direction: "column",
      xs: 6,
      md: 3,
    },
    mutual_info_frac: {
      label: "Mutual Information Fraction",
      type: "Counter",
      target: "config",
      placeholder: "Set mutual info fraction",
      path: "feature_engg.mutual_info.mutual_info_frac",
      showLabel: true,
      maxRange: 1.0,
      minRange: 0.01,
      xs: 6,
      md: 3,
    },
    use_top_n: {
      label: "Use Top N Features",
      type: "Check",
      target: "config",
      path: "feature_engg.mutual_info.use_top_n",
      direction: "column",
      xs: 6,
      md: 3,
    },
    top_n_features: {
      label: "Top N Features",
      type: "Counter",
      target: "config",
      placeholder: "Set top N features",
      path: "feature_engg.mutual_info.top_n_features",
      showLabel: true,
      maxRange: 100000,
      minRange: 1,
      xs: 6,
      md: 3,
    },

    backfill_time_series: {
      label: "Backfill Time Series",
      type: "Check",
      target: "config",
      path: "feature_engg.backfill_time_series",
      showLabel: true,
      xs: 12,
      md: 2,
    },

    sinusoidal_freq_max_count: {
      label: "Sinusoidal Frequency",
      type: "Counter",
      target: "config",
      placeholder: "Set top N features",
      path: "feature_engg.sinusoidal_freq_max_count",
      showLabel: true,
      maxRange: 20,
      minRange: 2,
      xs: 12,
      md: 10,
    },

    // Planner Adjustment Fields
    operation_name: {
      label: "Operation name",
      type: "AutoComplete",
      target: "adjust",
      placeholder: "Select",
      path: "operation",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 12,
      values: ["adjust_data"],
      disableClearable: true,
    },
    select_dimension: {
      label: "Select Dimension",
      type: "AutoComplete",
      target: "adjust",
      placeholder: "Select",
      path: "kwargs.dimension",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 6,
      values: "dimensionOptions", // This should be populated with "dimensionOptions"
      disableClearable: true,
    },
    select_value: {
      label: "Select Value",
      type: "TextInput",
      target: "adjust",
      placeholder: "type here...",
      path: "kwargs.value",
      showLabel: true,
      required: true,
      xs: 12,
      md: 6,
    },
    adjustments_start_date: {
      label: "Adjustments Start Date",
      type: "DatePicker",
      target: "adjust",
      path: "kwargs.date_range[0]",
      showLabel: true,
      xs: 12,
      md: 6,
    },
    adjustments_end_date: {
      label: "Adjustments End Date",
      type: "DatePicker",
      target: "adjust",
      path: "kwargs.date_range[1]",
      showLabel: true,
      xs: 12,
      md: 6,
    },
    adjustment_type: {
      label: "Adjustment type",
      type: "AutoComplete",
      target: "adjust",
      placeholder: "Select adjustment type",
      path: "kwargs.adjustment_type",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 6,
      values: [
        "uplift",
        "YoY",
        "cut_history",
        "stockout_correction",
        "replace_value",
        "uplift_by_value",
      ],
      valuesDict: {
        uplift: "Uplift",
        YoY: "YoY",
        cut_history: "Cut History",
        stockout_correction: "Stockout Correction",
        replace_value: "replace_value",
        uplift_by_value: "uplift_by_value",
      },
      disableClearable: true,
    },
    adjustment_value: {
      label: "Adjustment Value",
      type: "Counter",
      target: "adjust",
      placeholder: "Select adjustment value",
      path: "kwargs.adjustment_value",
      showLabel: true,
      maxRange: 1000,
      minRange: -1000,
      xs: 12,
      md: 6,
    },

    adjustment_time_steps: {
      label: "Time steps",
      type: "Counter",
      target: "adjust",
      placeholder: "Select adjustment value",
      path: "kwargs.time_steps",
      showLabel: true,
      maxRange: 1000,
      minRange: -1000,
      xs: 12,
      md: 6,
    },

    adjustment_future_history: {
      label: "Select Refrence Data",
      type: "AutoComplete",
      target: "adjust",
      placeholder: "Select",
      path: "kwargs.future_history",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 6,
      values: ["future", "history"],
      disableClearable: true,
    },
    // Exogenous Features Fields
    exogenous_feature_name: {
      label: "Exogenous Feature Name",
      type: "TextInput",
      target: "exogenous",
      path: "new_column",
      showLabel: true,
      placeholder: "Your feature name",
      required: true,
      xs: 12,
      md: 12,
    },
    enrichment_start_date_1: {
      label: "Enrichment Start Date",
      type: "DatePicker",
      target: "datePair",
      path: "start_dt",
      showLabel: true,
      xs: 12,
      md: 6,
    },
    enrichment_end_date_1: {
      label: "Enrichment End Date",
      type: "DatePicker",
      target: "datePair",
      path: "end_dt",
      showLabel: true,
      xs: 12,
      md: 6,
    },

    // Planner Enrichments Fields
    enrichment_operation_name: {
      label: "Operation name",
      type: "AutoComplete",
      target: "enrichment",
      placeholder: "Select",
      path: "operation",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 12,
      values: ["enrich_data"],
      disableClearable: true,
    },
    enrichment_select_dimension: {
      label: "Select Dimension",
      type: "AutoComplete",
      target: "enrichment",
      placeholder: "Select",
      path: "kwargs.dimension",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 6,
      values: "dimensionOptions", // This should be populated with "dimensionOptions"
      disableClearable: true,
    },
    enrichment_select_value: {
      label: "Select Value",
      type: "TextInput",
      target: "enrichment",
      placeholder: "type here...",
      path: "kwargs.value",
      showLabel: true,
      required: true,
      xs: 12,
      md: 6,
    },
    enrichment_start_date: {
      label: "Enrichment Start Date",
      type: "DatePicker",
      target: "enrichment",
      path: "kwargs.date_range[0]",
      showLabel: true,
      xs: 12,
      md: 6,
    },
    enrichment_end_date: {
      label: "Enrichment End Date",
      type: "DatePicker",
      target: "enrichment",
      path: "kwargs.date_range[1]",
      showLabel: true,
      xs: 12,
      md: 6,
    },
    enrichment_type: {
      label: "Enrichment type",
      type: "AutoComplete",
      target: "enrichment",
      placeholder: "Select enrichment type",
      path: "kwargs.enrichment_type",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 6,
      values: ["uplift", "upper_bound", "lower_bound", "offset"],
      disableClearable: true,
    },
    enrichment_value: {
      label: "Enrichment Value",
      type: "Counter",
      target: "enrichment",
      placeholder: "Select enrichment value",
      path: "kwargs.enrichment_value",
      showLabel: true,
      maxRange: 1000,
      minRange: -1000,
      xs: 12,
      md: 6,
    },
    dummy_value: {
      label: "dummyField",
      type: "ArrayEditor",
      target: "config",
      placeholder: "Enter Dummy value",
      path: "training.models.Xgboost.hyperparams.booster.params",
      showLabel: true,
      maxRange: 1000,
      minRange: -1000,
      xs: 12,
      md: 6,
    },

    //ml_ops fields

    instance_size: {
      label: "Select Instance Size",

      type: "AutoComplete",
      target: "config",
      placeholder: "Select Instance",
      path: "resource_config.instance_size",
      showLabel: true,
      disableClearable: true,
      xs: 12,
      md: 12,
      values: ["xLarge", "4xLarge", "8xLarge", "12xLarge"],
      valuesDict: {
        xLarge: "4vCPU, 16GB",
        "4xLarge": "16vCPU, 64GB",
        "8xLarge": "32vCPU, 128GB",
        "12xLarge": "48vCPU, 192GB",
      },
    },

    //Dashboard Settings
    // SNOP Setting

    forecast_data_reference_item_exp_path: {
      label: "Select Experiment",
      type: "AutoComplete",
      target: "forecast_data_reference_item",
      placeholder: "Select experiment",
      path: "exp_path",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 12,
      values: "experiments_list",
    },
    forecast_data_reference_item_forecast_type: {
      label: "Select Forecast Type",
      type: "AutoComplete",
      target: "forecast_data_reference_item",
      placeholder: "Select forecast type",
      path: "forecast_type",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 6,
      values: ["locked", "consensus"],
    },

    forecast_data_reference_item_column_tag: {
      label: "Select Column Tag",
      type: "AutoComplete",
      target: "forecast_data_reference_item",
      placeholder: "Select column tag",
      path: "column_tag",
      showLabel: true,
      isMultiSelect: false,
      xs: 12,
      md: 6,
      values: "date_columns",
      target_file: "scenario_planning/K_best/forecast/forecast_data_pivot.csv",
    },

    ts_id_view: {
      label: "Select View1 Granularity",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select granularity for view1",
      path: "scenario_plan.demand_alignment_report.ts_id_view1",
      showLabel: true,
      xs: 12,
      md: 6,
      values: ts_id_columns,
    },

    historical_horizon: {
      label: "Historical Horizon SnOP",
      type: "Counter",
      target: "config",
      placeholder: "Set Historical Horizon SnOP",
      path: "scenario_plan.historical_horizon_snop",
      showLabel: true,
      maxRange: 1000,
      minRange: 0,
      xs: 12,
      md: 6,
    },

    zero_sales_lag: {
      label: "Zero Sales Check (N Periods)",
      type: "Counter",
      target: "config",
      placeholder: "Zero Sales Check (N Periods)",
      path: "scenario_plan.demand_alignment_report.zero_sales_lag",
      showLabel: true,
      maxRange: 1000,
      minRange: 0,
      xs: 12,
      md: 6,
    },

    zero_forecast_horizon: {
      label: "Zero Forecast Check (N Periods)",
      type: "Counter",
      target: "config",
      placeholder: "Zero Forecast Check (N Periods)",
      path: "scenario_plan.demand_alignment_report.zero_forecast_horizon",
      showLabel: true,
      maxRange: 1000,
      minRange: 0,
      xs: 12,
      md: 6,
    },

    calc_dimensions_accuracy: {
      label: "Calculate Dimension Accuracy?",
      type: "Check",
      target: "config",
      path: "scenario_plan.demand_alignment_report.calc_dimensions_accuracy",
      showLabel: true,
      xs: 12,
      md: 3,
    },
    dimensions_for_accuracy: {
      label: "Select Dimensions for Accuracy",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Select Dimensions for Accuracy",
      path: "scenario_plan.demand_alignment_report.dimensions_for_accuracy",
      showLabel: true,
      xs: 12,
      md: 9,
      values: [
        ...ts_id_columns,
        ...(config?.scenario_plan?.post_model_demand_pattern?.dimensions || []),
        "cluster",
        "Lifestage"
        
      ],
    },

    enable_aggregation: {
      label: "Enable Aggregation",
      type: "Check",
      target: "config",
      path: "scenario_plan.demand_alignment_report.enable_aggregation",
      showLabel: true,
      xs: 12,
      md: 3,
    },
    create_future_locked_forecast_data: {
      label: "Create future locked forecast data",
      type: "Check",
      target: "config",
      path: "scenario_plan.demand_alignment_report.create_future_locked_forecast_data",
      showLabel: true,
      xs: 12,
      md: 3,
    },
    create_future_sales_data: {
      label: "Create future sales data",
      type: "Check",
      target: "config",
      path: "scenario_plan.demand_alignment_report.create_future_sales_data",
      showLabel: true,
      xs: 12,
      md: 3,
    },

    consensus_overwrite: {
      label: "Consensus Overwrite?",
      type: "Check",
      target: "config",
      path: "scenario_plan.demand_alignment_report.consensus_overwrite",
      showLabel: true,
      xs: 12,
      md: 3,
    },
    convert_to_integer: {
      label: "Convert to Integer",
      type: "Check",
      target: "config",
      path: "scenario_plan.convert_to_integer",
      showLabel: true,
      xs: 12,
      md: 4,
    },

    current_sales_including_open_po: {
      label: "Current Sales including Open PO",
      type: "Check",
      target: "config",
      path: "scenario_plan.current_sales_including_open_po",
      showLabel: true,
      xs: 12,
      md: 4,
    },

    view0_report_name: {
      label: "Default Report Name",
      type: "TextInput",
      target: "config",
      placeholder: "Enter View 0 Report Name",
      path: "scenario_plan.demand_alignment_report.view0_report_name",
      showLabel: true,
      xs: 12,
      md: 6,
    },

    view1_report_name: {
      label: "View 1 Report Name",
      type: "TextInput",
      target: "config",
      placeholder: "Enter View 1 Report Name",
      path: "scenario_plan.demand_alignment_report.view1_report_name",
      showLabel: true,
      xs: 12,
      md: 6,
    },

    accuracy_calculation: {
      label: "Accuracy Calculation",
      type: "Check",
      target: "config",
      path: "scenario_plan.accuracy_calculation",
      showLabel: true,
      xs: 12,
      md: 4,
    },

    // General Settings

    file_type: {
      label: "Save Format",

      type: "AutoComplete",
      target: "config",
      placeholder: "Select File Formate",
      path: "scenario_plan.file_type",
      isMultiSelect: true,
      showLabel: true,
      xs: 12,
      md: 12,
      values: ["csv", "parquet"],
      valuesDict: {
        csv: "CSV",
        parquet: "Parquet",
      },
    },
    show_forecasting_pivot_disaggregated: {
      label: "Show Forecasting Pivot Disaggregated",
      type: "Check",
      target: "config",
      path: "dashboard_settings.show_forecasting_pivot_disaggregated",
      showLabel: true,
      direction: "column",
      xs: 12,
      md: 4,
    },
    hide_forecasting_pivot_table: {
      label: "Hide Forecasting Pivot Table?",
      type: "Check",
      target: "config",
      path: "dashboard_settings.hide_forecasting_pivot_table",
      showLabel: true,
      xs: 12,
      md: 4,
    },
    align_period_labels_to_start: {
      label: "Align period labels to start?",
      type: "Check",
      target: "config",
      path: "dashboard_settings.align_period_labels_to_start",
      showLabel: true,
      xs: 12,
      md: 4,
    },

    // HyperParamerters
    // XGboost

    xg_boost_booster: {
      label: "Booster",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgboost.hyperparams.booster",
      isFixed: true,
      options: ["choice"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    xg_boost_verbose: {
      label: "Verbose",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgboost.hyperparams.verbose",
      isFixed: false,
      options: ["choice", "loguniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    xg_boost_learning_rate: {
      label: "Learning Rate",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgboost.hyperparams.learning_rate",
      isFixed: false,
      options: ["choice", "loguniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },

    xg_boost_max_depth: {
      label: "Max Depth",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgboost.hyperparams.max_depth",
      isFixed: false,
      options: ["choice", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },

    xg_boost_reg_lambda: {
      label: "Regex Lambda",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgboost.hyperparams.reg_lambda",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },

    xg_boost_n_estimators: {
      label: "Learning Rate",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgboost.hyperparams.n_estimators",
      isFixed: false,
      options: ["choice", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },

    xg_boost_multiprocessing: {
      label: "Multiprocessing",
      type: "Check",
      target: "config",
      path: "training.models.Xgboost.multiprocessing",
      direction: "column",
      xs: 12,
      md: 4,
    },

    xg_boost_best_trials: {
      label: "Best trials",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "training.models.Xgboost.best_trials",
      showLabel: true,
      maxRange: 100,
      minRange: 0,
      xs: 12,
      md: 8,
    },

    xg_boost_feature_group: {
      label: "Select Feature Group to be created",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "training.models.Xgboost.feature_groups",
      showLabel: true,
      xs: 12,
      md: 12,
      values: featuresArray,
    },

    xg_boost_scale: {
      label: "Scale Features",
      type: "Check",
      target: "config",
      path: "training.models.Xgboost.scale",
      direction: "column",
      xs: 6,
      md: 3,
    },
    xg_boost_exclude_cols: {
      label: "Exclude Columns",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select columns to exclude",
      path: "training.models.Xgboost.exclude_cols",
      showLabel: true,
      isMultiSelect: true,
      xs: 12,
      md: 6,
      values: taggedColumns, // This should be populated with available column names
    },

    xg_boost_max_evals: {
      label: "Maximum Evaluations",
      type: "Counter",
      target: "config",
      placeholder: "Set max evaluations",
      path: "training.models.Xgboost.max_evals",
      showLabel: true,
      maxRange: 1000,
      minRange: 1,
      xs: 6,
      md: 3,
    },
    xg_boost_early_stopping_rounds: {
      label: "Early Stopping Rounds",
      type: "Counter",
      target: "config",
      placeholder: "Set early stopping rounds",
      path: "training.models.Xgboost.early_stopping_rounds",
      showLabel: true,
      maxRange: 1000,
      minRange: 1,
      xs: 12,
      md: 12,
    },

    // LGBM Fields

    lgbm_boosting_type: {
      label: "Boosting Type",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.boosting_type",
      isFixed: false,
      options: ["choice"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_objective: {
      label: "Objective",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.objective",
      isFixed: false,
      options: ["choice"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_verbose: {
      label: "Verbose",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.verbose",
      isFixed: false,
      options: ["choice"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_random_state: {
      label: "Random State",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.random_state",
      isFixed: false,
      options: ["choice"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_learning_rate: {
      label: "Learning Rate",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.learning_rate",
      isFixed: false,
      options: ["choice", "loguniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_max_depth: {
      label: "Max Depth",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.max_depth",
      isFixed: false,
      options: ["choice", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_num_leaves: {
      label: "Number of Leaves",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.num_leaves",
      isFixed: false,
      options: ["choice", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_reg_lambda: {
      label: "Reg Lambda",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.reg_lambda",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_n_estimators: {
      label: "Number of Estimators",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Lgbm.hyperparams.n_estimators",
      isFixed: false,
      options: ["choice", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    lgbm_multiprocessing: {
      label: "Multiprocessing",
      type: "Check",
      target: "config",
      path: "training.models.Lgbm.multiprocessing",
      direction: "column",
      xs: 12,
      md: 4,
    },
    lgbm_best_trials: {
      label: "Best trials",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "training.models.Lgbm.best_trials",
      showLabel: true,
      maxRange: 10,
      minRange: 1,
      xs: 12,
      md: 8,
    },
    lgbm_feature_group: {
      label: "Select Feature Group to be created",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "training.models.Lgbm.feature_groups",
      showLabel: true,
      xs: 12,
      md: 12,
      values: featuresArray,
    },
    lgbm_scale: {
      label: "Scale Features",
      type: "Check",
      target: "config",
      path: "training.models.Lgbm.scale",
      direction: "column",
      xs: 6,
      md: 3,
    },
    lgbm_exclude_cols: {
      label: "Exclude Columns",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select columns to exclude",
      path: "training.models.Lgbm.exclude_cols",
      showLabel: true,
      isMultiSelect: true,
      xs: 12,
      md: 6,
      values: taggedColumns,
    },
    lgbm_max_evals: {
      label: "Maximum Evaluations",
      type: "Counter",
      target: "config",
      placeholder: "Set max evaluations",
      path: "training.models.Lgbm.max_evals",
      showLabel: true,
      maxRange: 1000,
      minRange: 1,
      xs: 6,
      md: 3,
    },
    lgbm_early_stopping_rounds: {
      label: "Early Stopping Rounds",
      type: "Counter",
      target: "config",
      placeholder: "Set early stopping rounds",
      path: "training.models.Lgbm.early_stopping_rounds",
      showLabel: true,
      maxRange: 1000,
      minRange: 1,
      xs: 12,
      md: 12,
    },

    // XGBLinear Fields
    xgb_linear_booster: {
      label: "Booster",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgblinear.hyperparams.booster",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    xgb_linear_verbose: {
      label: "Verbose",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgblinear.hyperparams.verbose",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    xgb_linear_max_depth: {
      label: "Max Depth",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgblinear.hyperparams.max_depth",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    xgb_linear_learning_rate: {
      label: "Learning Rate",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgblinear.hyperparams.learning_rate",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    xgb_linear_reg_lambda: {
      label: "Reg Lambda",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgblinear.hyperparams.reg_lambda",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    xgb_linear_n_estimators: {
      label: "Number of Estimators",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.Xgblinear.hyperparams.n_estimators",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    xgb_linear_multiprocessing: {
      label: "Multiprocessing",
      type: "Check",
      target: "config",
      path: "training.models.Xgblinear.multiprocessing",
      direction: "column",
      xs: 12,
      md: 4,
    },
    xgb_linear_best_trials: {
      label: "Best trials",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "training.models.Xgblinear.best_trials",
      showLabel: true,
      maxRange: 10,
      minRange: 1,
      xs: 12,
      md: 8,
    },
    xgb_linear_feature_group: {
      label: "Select Feature Group to be created",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "training.models.Xgblinear.feature_groups",
      showLabel: true,
      xs: 12,
      md: 12,
      values: featuresArray,
    },
    xgb_linear_scale: {
      label: "Scale Features",
      type: "Check",
      target: "config",
      path: "training.models.Xgblinear.scale",
      direction: "column",
      xs: 6,
      md: 3,
    },
    xgb_linear_exclude_cols: {
      label: "Exclude Columns",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select columns to exclude",
      path: "training.models.Xgblinear.exclude_cols",
      showLabel: true,
      isMultiSelect: true,
      xs: 12,
      md: 6,
      values: taggedColumns,
    },
    xgb_linear_max_evals: {
      label: "Maximum Evaluations",
      type: "Counter",
      target: "config",
      placeholder: "Set max evaluations",
      path: "training.models.Xgblinear.max_evals",
      showLabel: true,
      maxRange: 1000,
      minRange: 1,
      xs: 6,
      md: 3,
    },
    xgb_linear_early_stopping_rounds: {
      label: "Early Stopping Rounds",
      type: "Counter",
      target: "config",
      placeholder: "Set early stopping rounds",
      path: "training.models.Xgblinear.early_stopping_rounds",
      showLabel: true,
      maxRange: 1000,
      minRange: 1,
      xs: 12,
      md: 12,
    },

    // Random Forest Fields
    rf_max_depth: {
      label: "Max Depth",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.RandomForest.hyperparams.max_depth",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    rf_min_samples_leaf: {
      label: "Min Samples Leaf",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.RandomForest.hyperparams.min_samples_leaf",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    rf_n_estimators: {
      label: "Number of Estimators",
      type: "hyperparameter",
      target: "config",
      placeholder: "Enter value",
      path: "training.models.RandomForest.hyperparams.n_estimators",
      isFixed: false,
      options: ["choice", "loguniform", "quniform"],
      showLabel: true,
      xs: 12,
      md: 6,
    },
    rf_multiprocessing: {
      label: "Multiprocessing",
      type: "Check",
      target: "config",
      path: "training.models.RandomForest.multiprocessing",
      direction: "column",
      xs: 12,
      md: 4,
    },
    rf_best_trials: {
      label: "Best trials",
      type: "Counter",
      target: "config",
      placeholder: "Set your count",
      path: "training.models.RandomForest.best_trials",
      showLabel: true,
      maxRange: 10,
      minRange: 1,
      xs: 12,
      md: 8,
    },
    rf_feature_group: {
      label: "Select Feature Group to be created",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "training.models.RandomForest.feature_groups",
      showLabel: true,
      xs: 12,
      md: 12,
      values: featuresArray,
    },
    rf_scale: {
      label: "Scale Features",
      type: "Check",
      target: "config",
      path: "training.models.RandomForest.scale",
      direction: "column",
      xs: 6,
      md: 3,
    },
    rf_exclude_cols: {
      label: "Exclude Columns",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select columns to exclude",
      path: "training.models.RandomForest.exclude_cols",
      showLabel: true,
      isMultiSelect: true,
      xs: 12,
      md: 6,
      values: taggedColumns,
    },
    rf_max_evals: {
      label: "Maximum Evaluations",
      type: "Counter",
      target: "config",
      placeholder: "Set max evaluations",
      path: "training.models.RandomForest.max_evals",
      showLabel: true,
      maxRange: 1000,
      minRange: 1,
      xs: 6,
      md: 3,
    },

    // MLP Fields
    mlp_multiprocessing: {
      label: "Multiprocessing",
      type: "Check",
      target: "config",
      path: "training.models.MLP.multiprocessing",
      direction: "column",
      xs: 12,
      md: 2,
    },
    mlp_model_weights: {
      label: "Model Weights Filename",
      type: "TextInput",
      target: "config",
      placeholder: "Enter model weights filename",
      path: "training.models.MLP.model_weights_fname",
      showLabel: true,
      xs: 12,
      md: 6,
    },

    mlp_feature_group: {
      label: "Select Feature Group to be created",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "training.models.MLP.feature_groups",
      showLabel: true,
      xs: 12,
      md: 10,
      values: featuresArray,
    },

    mlp_feature_group_type: {
      label: "Feature Group Type",
      type: "Check",
      target: "config",
      path: "training.models.MLP.feature_group_type",
      direction: "column",
      xs: 6,
      md: 2,
    },
    mlp_scale: {
      label: "Scale Features",
      type: "Check",
      target: "config",
      path: "training.models.MLP.scale",
      direction: "column",
      xs: 6,
      md: 2,
    },

    mlp_exclude_cols: {
      label: "Exclude Columns",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select columns to exclude",
      path: "training.models.MLP.exclude_cols",
      showLabel: true,
      isMultiSelect: true,
      xs: 12,
      md: 8,
      values: taggedColumns,
    },
    mlp_hyperparam_trials: {
      label: "Hyperparameter Trials",
      type: "Check",
      target: "config",
      path: "training.models.MLP.hyperparam_trials",
      direction: "column",
      xs: 6,
      md: 2,
    },
    mlp_random_sample: {
      label: "Random Sample",
      type: "Check",
      target: "config",
      path: "training.models.MLP.random_sample",
      direction: "column",
      xs: 6,
      md: 2,
    },

    mlp_trials: {
      label: "Number of Trials",
      type: "Counter",
      target: "config",
      placeholder: "Set number of trials",
      path: "training.models.MLP.trials",
      showLabel: true,
      maxRange: 100,
      minRange: 1,
      xs: 6,
      md: 8,
    },

    mlp_trial_params: {
      label: "Trial Parameters",
      type: "custom",
      component: "TrialParamsManager",
      path: "training.models.MLP.trial_params",
      xs: 12,
      md: 12,
      modelType: "MLP",
    },

    mlp_params: {
      label: "MLP Parameters",
      type: "nested",
      target: "config",
      path: "training.models.MLP.params",
      showLabel: true,
      xs: 12,
      md: 12,
      fields: {
        network_params: {
          label: "Network Parameters",
          type: "section",
          fields: {
            epochs: {
              label: "Epochs",
              type: "Counter",
              placeholder: "Set number of epochs",
              maxRange: 100,
              minRange: 1,
              xs: 6,
              md: 4,
              path: "training.models.MLP.params.network_params.epochs",
            },
            compression_factor: {
              label: "Compression Factor",
              type: "Counter",
              placeholder: "Set compression factor",
              maxRange: 100,
              minRange: 1,
              xs: 6,
              md: 4,
              path: "training.models.MLP.params.network_params.compression_factor",
            },
            max_embedding: {
              label: "Max Embedding",
              type: "Counter",
              placeholder: "Set max embedding",
              maxRange: 100,
              minRange: 1,
              xs: 6,
              md: 4,
              path: "training.models.MLP.params.network_params.max_embedding",
            },
            driver_factor: {
              label: "Driver Factor",
              type: "Counter",
              placeholder: "Set driver factor",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 6,
              path: "training.models.MLP.params.network_params.driver_factor",
            },
            dropout: {
              label: "Dropout",
              type: "Counter",
              placeholder: "Set dropout rate",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 6,
              path: "training.models.MLP.params.network_params.dropout",
            },
          },
        },
        dataloader_params: {
          label: "Dataloader Parameters",
          type: "section",
          fields: {
            shuffle: {
              label: "Shuffle Data",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.MLP.params.dataloader_params.shuffle",
            },
            batch_size: {
              label: "Batch Size",
              type: "Counter",
              placeholder: "Set batch size",
              maxRange: 1000,
              minRange: 0,
              xs: 6,
              md: 5,
              path: "training.models.MLP.params.dataloader_params.batch_size",
            },

            num_workers: {
              label: "Number of Workers",
              type: "Counter",
              placeholder: "Set number of workers",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 5,
              path: "training.models.MLP.params.dataloader_params.num_workers",
            },
          },
        },
        optimizer_params: {
          label: "Optimizer Parameters",
          type: "section",
          fields: {
            RMSprop: {
              label: "RMSprop Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.MLP.params.optimizer_params.RMSprop.lr",
                },
                alpha: {
                  label: "Alpha",
                  type: "Counter",
                  placeholder: "Set alpha",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.MLP.params.optimizer_params.RMSprop.alpha",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.MLP.params.optimizer_params.RMSprop.weight_decay",
                },
              },
            },
            SGD: {
              label: "SGD Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.MLP.params.optimizer_params.SGD.lr",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.MLP.params.optimizer_params.SGD.weight_decay",
                },
              },
            },
            Adam: {
              label: "Adam Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.MLP.params.optimizer_params.Adam.lr",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.MLP.params.optimizer_params.Adam.weight_decay",
                },
              },
            },
          },
        },
        scheduler_params: {
          label: "Scheduler Parameters",
          type: "section",
          fields: {
            ReduceLROnPlateau: {
              label: "ReduceLROnPlateau Settings",
              type: "subsection",
              fields: {
                mode: {
                  label: "Mode",
                  type: "AutoComplete",
                  placeholder: "Select mode",
                  values: ["min", "max"],
                  xs: 6,
                  md: 3,
                  path: "training.models.MLP.params.scheduler_params.ReduceLROnPlateau.mode",
                },
                factor: {
                  label: "Factor",
                  type: "Counter",
                  placeholder: "Set factor",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.MLP.params.scheduler_params.ReduceLROnPlateau.factor",
                },
                patience: {
                  label: "Patience",
                  type: "Counter",
                  placeholder: "Set patience",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.MLP.params.scheduler_params.ReduceLROnPlateau.patience",
                },
                min_lr: {
                  label: "Minimum Learning Rate",
                  type: "Counter",
                  placeholder: "Set minimum learning rate",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.MLP.params.scheduler_params.ReduceLROnPlateau.min_lr",
                },
              },
            },
            CyclicLR: {
              label: "CyclicLR Settings",
              type: "subsection",
              fields: {
                base_lr: {
                  label: "Base Learning Rate",
                  type: "Counter",
                  placeholder: "Set base learning rate",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.MLP.params.scheduler_params.CyclicLR.base_lr",
                },
                max_lr: {
                  label: "Max Learning Rate",
                  type: "Counter",
                  placeholder: "Set max learning rate",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.MLP.params.scheduler_params.CyclicLR.max_lr",
                },

                cycle_momentum: {
                  label: "Cycle Momentum",
                  type: "Check",
                  xs: 6,
                  md: 2,
                  path: "training.models.MLP.params.scheduler_params.CyclicLR.cycle_momentum",
                },
                step_size_up: {
                  label: "Step Size Up",
                  type: "Counter",
                  placeholder: "Set step size up",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 10,
                  path: "training.models.MLP.params.scheduler_params.CyclicLR.step_size_up",
                },
              },
            },
          },
        },
        SWA_params: {
          label: "SWA Parameters",
          type: "section",
          fields: {
            swa_start: {
              label: "SWA Start Epoch",
              type: "Counter",
              placeholder: "Set SWA start epoch",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.MLP.params.SWA_params.swa_start",
            },
            swa_freq: {
              label: "SWA Frequency",
              type: "Counter",
              placeholder: "Set SWA frequency",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.MLP.params.SWA_params.swa_freq",
            },
            swa_lr: {
              label: "SWA Learning Rate",
              type: "Counter",
              placeholder: "Set SWA learning rate",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.MLP.params.SWA_params.swa_lr",
            },
          },
        },
        callback_params: {
          label: "Callback Parameters",
          type: "section",
          fields: {
            earlystopping: {
              label: "Early Stopping",
              type: "subsection",
              fields: {
                patience: {
                  label: "Patience",
                  type: "Counter",
                  placeholder: "Set early stopping patience",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 12,
                  path: "training.models.MLP.params.callback_params.earlystopping.patience",
                },
              },
            },
          },
        },
        regularization: {
          label: "Regularization",
          type: "section",
          fields: {
            l2_norm: {
              label: "Use L2 Normalization",
              type: "Check",
              xs: 6,
              md: 4,
              path: "training.models.MLP.params.regularization.l2_norm",
            },
            reg_param: {
              label: "Regularization Parameters",
              type: "subsection",
              fields: {
                reg_loss: {
                  label: "Regularization Loss",
                  type: "AutoComplete",
                  placeholder: "Select regularization loss",
                  values: [],
                  xs: 6,
                  md: 6,
                  path: "training.models.MLP.params.regularization.reg_param.reg_loss",
                },
                lmbda: {
                  label: "Lambda",
                  type: "Counter",
                  placeholder: "Set lambda value",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.MLP.params.regularization.reg_param.lmbda",
                },
              },
            },
          },
        },
        parameter_averaging: {
          label: "Parameter Averaging",
          type: "section",
          fields: {
            window: {
              label: "Averaging Window",
              type: "Counter",
              placeholder: "Set averaging window",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 12,
              path: "training.models.MLP.params.parameter_averaging.window",
            },
          },
        },
        Tlearn_params: {
          label: "Transfer Learning Parameters",
          type: "section",
          fields: {
            specific_FC_layers: {
              label: "Specific FC Layers",
              type: "Counter",
              placeholder: "Set number of FC layers",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 12,
              path: "training.models.MLP.params.Tlearn_params.specific_FC_layers",
            },
          },
        },
        default_params: {
          label: "Default Parameters",
          type: "section",
          fields: {
            SWA: {
              label: "SWA",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.MLP.default_params.SWA",
            },
            optimizer: {
              label: "Optimizer",
              type: "AutoComplete",
              placeholder: "Select optimizer",
              values: ["RMSprop", "SGD", "Adam"],
              xs: 6,
              md: 5,
              path: "training.models.MLP.default_params.optimizer",
            },
            scheduler: {
              label: "Scheduler",
              type: "AutoComplete",
              placeholder: "Select scheduler",
              values: ["ReduceLROnPlateau", "CyclicLR"],
              xs: 6,
              md: 5,
              path: "training.models.MLP.default_params.scheduler",
            },
          },
        },
        Transferlearn_params: {
          label: "Transfer Learning Parameters",
          type: "section",
          fields: {
            SWA: {
              label: "SWA",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.MLP.Transferlearn_params.SWA",
            },
            model_weights: {
              label: "Use Model Weights",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.MLP.Transferlearn_params.model_weights",
            },
            optimizer: {
              label: "Optimizer",
              type: "AutoComplete",
              placeholder: "Select optimizer",
              values: ["RMSprop", "SGD", "Adam"],
              xs: 6,
              md: 4,
              path: "training.models.MLP.Transferlearn_params.optimizer",
            },
            scheduler: {
              label: "Scheduler",
              type: "AutoComplete",
              placeholder: "Select scheduler",
              values: ["ReduceLROnPlateau", "CyclicLR"],
              xs: 6,
              md: 4,
              path: "training.models.MLP.Transferlearn_params.scheduler",
            },
          },
        },
      },
    },

    // LSTM feilds
    lstm_multiprocessing: {
      label: "Multiprocessing",
      type: "Check",
      target: "config",
      path: "training.models.LSTM.multiprocessing",
      direction: "column",
      xs: 12,
      md: 2,
    },
    lstm_model_weights: {
      label: "Model Weights Filename",
      type: "TextInput",
      target: "config",
      placeholder: "Enter model weights filename",
      path: "training.models.LSTM.model_weights_fname",
      showLabel: true,
      xs: 12,
      md: 6,
    },

    lstm_feature_group: {
      label: "Select Feature Group to be created",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "training.models.LSTM.feature_groups",
      showLabel: true,
      xs: 12,
      md: 10,
      values: featuresArray,
    },

    lstm_feature_group_type: {
      label: "Feature Group Type",
      type: "Check",
      target: "config",
      path: "training.models.LSTM.feature_group_type",
      direction: "column",
      xs: 6,
      md: 2,
    },
    lstm_scale: {
      label: "Scale Features",
      type: "Check",
      target: "config",
      path: "training.models.LSTM.scale",
      direction: "column",
      xs: 6,
      md: 2,
    },

    lstm_exclude_cols: {
      label: "Exclude Columns",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select columns to exclude",
      path: "training.models.LSTM.exclude_cols",
      showLabel: true,
      isMultiSelect: true,
      xs: 12,
      md: 8,
      values: taggedColumns,
    },
    lstm_hyperparam_trials: {
      label: "Hyperparameter Trials",
      type: "Check",
      target: "config",
      path: "training.models.LSTM.hyperparam_trials",
      direction: "column",
      xs: 6,
      md: 2,
    },
    lstm_random_sample: {
      label: "Random Sample",
      type: "Check",
      target: "config",
      path: "training.models.LSTM.random_sample",
      direction: "column",
      xs: 6,
      md: 2,
    },
    lstm_trials: {
      label: "Number of Trials",
      type: "Counter",
      target: "config",
      placeholder: "Set number of trials",
      path: "training.models.LSTM.trials",
      showLabel: true,
      maxRange: 100,
      minRange: 1,
      xs: 6,
      md: 8,
    },

    lstm_trial_params: {
      label: "Trial Parameters",
      type: "custom",
      component: "TrialParamsManager",
      path: "training.models.LSTM.trial_params",
      xs: 12,
      md: 12,
      modelType: "LSTM",
    },

    lstm_params: {
      label: "LSTM Parameters",
      type: "nested",
      target: "config",
      path: "training.models.LSTM.params",
      showLabel: true,
      xs: 12,
      md: 12,
      fields: {
        network_params: {
          label: "Network Parameters",
          type: "section",
          fields: {
            epochs: {
              label: "Epochs",
              type: "Counter",
              placeholder: "Set number of epochs",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.LSTM.params.network_params.epochs",
            },
            compression_factor: {
              label: "Compression Factor",
              type: "Counter",
              placeholder: "Set compression factor",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.LSTM.params.network_params.compression_factor",
            },
            max_embedding: {
              label: "Max Embedding",
              type: "Counter",
              placeholder: "Set max embedding",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.LSTM.params.network_params.max_embedding",
            },
          },
        },
        dataloader_params: {
          label: "Dataloader Parameters",
          type: "section",
          fields: {
            shuffle: {
              label: "Shuffle Data",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.LSTM.params.dataloader_params.shuffle",
            },
            batch_size: {
              label: "Batch Size",
              type: "Counter",
              placeholder: "Set batch size",
              maxRange: 1024,
              minRange: 0,
              xs: 6,
              md: 5,
              path: "training.models.LSTM.params.dataloader_params.batch_size",
            },

            num_workers: {
              label: "Number of Workers",
              type: "Counter",
              placeholder: "Set number of workers",
              maxRange: 16,
              minRange: 0,
              xs: 6,
              md: 5,
              path: "training.models.LSTM.params.dataloader_params.num_workers",
            },
          },
        },
        LSTM_params: {
          label: "LSTM Specific Parameters",
          type: "section",
          fields: {
            lstm_layers: {
              label: "LSTM Layers",
              type: "Counter",
              placeholder: "Set number of LSTM layers",
              maxRange: 10,
              minRange: 0,
              xs: 12,
              md: 12,
              path: "training.models.LSTM.params.LSTM_params.lstm_layers",
            },
          },
        },
        optimizer_params: {
          label: "Optimizer Parameters",
          type: "section",
          fields: {
            RMSprop: {
              label: "RMSprop Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.LSTM.params.optimizer_params.RMSprop.lr",
                },
                alpha: {
                  label: "Alpha",
                  type: "Counter",
                  placeholder: "Set alpha",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.LSTM.params.optimizer_params.RMSprop.alpha",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.LSTM.params.optimizer_params.RMSprop.weight_decay",
                },
              },
            },
            SGD: {
              label: "SGD Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.LSTM.params.optimizer_params.SGD.lr",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.LSTM.params.optimizer_params.SGD.weight_decay",
                },
              },
            },
            Adam: {
              label: "Adam Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.LSTM.params.optimizer_params.Adam.lr",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.LSTM.params.optimizer_params.Adam.weight_decay",
                },
              },
            },
          },
        },
        scheduler_params: {
          label: "Scheduler Parameters",
          type: "section",
          fields: {
            CyclicLR: {
              label: "CyclicLR Settings",
              type: "subsection",
              fields: {
                cycle_momentum: {
                  label: "Cycle Momentum",
                  type: "Check",
                  xs: 6,
                  md: 2,
                  path: "training.models.LSTM.params.scheduler_params.CyclicLR.cycle_momentum",
                },
                base_lr: {
                  label: "Base Learning Rate",
                  type: "Counter",
                  placeholder: "Set base learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.LSTM.params.scheduler_params.CyclicLR.base_lr",
                },
                max_lr: {
                  label: "Max Learning Rate",
                  type: "Counter",
                  placeholder: "Set max learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.LSTM.params.scheduler_params.CyclicLR.max_lr",
                },
                step_size_up: {
                  label: "Step Size Up",
                  type: "Counter",
                  placeholder: "Set step size up",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.LSTM.params.scheduler_params.CyclicLR.step_size_up",
                },
              },
            },
            ReduceLROnPlateau: {
              label: "ReduceLROnPlateau Settings",
              type: "subsection",
              fields: {
                mode: {
                  label: "Mode",
                  type: "AutoComplete",
                  placeholder: "Select mode",
                  values: ["min", "max"],
                  xs: 6,
                  md: 3,
                  path: "training.models.LSTM.params.scheduler_params.ReduceLROnPlateau.mode",
                },
                factor: {
                  label: "Factor",
                  type: "Counter",
                  placeholder: "Set factor",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.LSTM.params.scheduler_params.ReduceLROnPlateau.factor",
                },
                patience: {
                  label: "Patience",
                  type: "Counter",
                  placeholder: "Set patience",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.LSTM.params.scheduler_params.ReduceLROnPlateau.patience",
                },
                min_lr: {
                  label: "Minimum Learning Rate",
                  type: "Counter",
                  placeholder: "Set minimum learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.LSTM.params.scheduler_params.ReduceLROnPlateau.min_lr",
                },
              },
            },
          },
        },
        SWA_params: {
          label: "SWA Parameters",
          type: "section",
          fields: {
            swa_start: {
              label: "SWA Start Epoch",
              type: "Counter",
              placeholder: "Set SWA start epoch",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.LSTM.params.SWA_params.swa_start",
            },
            swa_freq: {
              label: "SWA Frequency",
              type: "Counter",
              placeholder: "Set SWA frequency",
              maxRange: 100,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.LSTM.params.SWA_params.swa_freq",
            },
            swa_lr: {
              label: "SWA Learning Rate",
              type: "Counter",
              placeholder: "Set SWA learning rate",
              maxRange: 1,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.LSTM.params.SWA_params.swa_lr",
            },
          },
        },
        callback_params: {
          label: "Callback Parameters",
          type: "section",
          fields: {
            earlystopping: {
              label: "Early Stopping",
              type: "subsection",
              fields: {
                patience: {
                  label: "Patience",
                  type: "Counter",
                  placeholder: "Set early stopping patience",
                  maxRange: 100,
                  minRange: 0,
                  xs: 12,
                  md: 12,
                  path: "training.models.LSTM.params.callback_params.earlystopping.patience",
                },
              },
            },
          },
        },
        regularization: {
          label: "Regularization",
          type: "section",
          fields: {
            l2_norm: {
              label: "Use L2 Normalization",
              type: "Check",
              xs: 6,
              md: 4,
              path: "training.models.LSTM.params.regularization.l2_norm",
            },
            reg_param: {
              label: "Regularization Parameters",
              type: "subsection",
              fields: {
                reg_loss: {
                  label: "Regularization Loss",
                  type: "AutoComplete",
                  placeholder: "Select regularization loss",
                  values: [, null],
                  xs: 6,
                  md: 6,
                  path: "training.models.LSTM.params.regularization.reg_param.reg_loss",
                },
                lmbda: {
                  label: "Lambda",
                  type: "Counter",
                  placeholder: "Set lambda value",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.LSTM.params.regularization.reg_param.lmbda",
                },
              },
            },
          },
        },
        parameter_averaging: {
          label: "Parameter Averaging",
          type: "section",
          fields: {
            window: {
              label: "Averaging Window",
              type: "Counter",
              placeholder: "Set averaging window",
              maxRange: 100,
              minRange: 0,
              xs: 12,
              md: 12,
              path: "training.models.LSTM.params.parameter_averaging.window",
            },
          },
        },
        Tlearn_params: {
          label: "Transfer Learning Parameters",
          type: "section",
          fields: {
            specific_FC_layers: {
              label: "Specific FC Layers",
              type: "Counter",
              placeholder: "Set number of FC layers",
              maxRange: 100,
              minRange: 0,
              xs: 12,
              md: 12,
              path: "training.models.LSTM.params.Tlearn_params.specific_FC_layers",
            },
          },
        },

        default_params: {
          label: "Default Parameters",
          type: "section",
          fields: {
            SWA: {
              label: "SWA",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.LSTM.default_params.SWA",
            },
            optimizer: {
              label: "Optimizer",
              type: "AutoComplete",
              placeholder: "Select optimizer",
              values: ["RMSprop", "SGD", "Adam"],
              xs: 6,
              md: 5,
              path: "training.models.LSTM.default_params.optimizer",
            },
            scheduler: {
              label: "Scheduler",
              type: "AutoComplete",
              placeholder: "Select scheduler",
              values: ["ReduceLROnPlateau", "CyclicLR"],
              xs: 6,
              md: 5,
              path: "training.models.LSTM.default_params.scheduler",
            },

            feature_group_type: {
              label: "Feature Group Type",
              type: "AutoComplete",
              placeholder: "Select feature group type",
              values: ["feature_group_type1", "feature_group_type2"],
              xs: 12,
              md: 12,
              path: "training.models.LSTM.default_params.feature_group_type",
            },
          },
        },
        Transferlearn_params: {
          label: "Transfer Learning Parameters",
          type: "section",
          fields: {
            SWA: {
              label: "SWA",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.LSTM.Transferlearn_params.SWA",
            },
            model_weights: {
              label: "Use Model Weights",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.LSTM.Transferlearn_params.model_weights",
            },
            optimizer: {
              label: "Optimizer",
              type: "AutoComplete",
              placeholder: "Select optimizer",
              values: ["RMSprop", "SGD", "Adam"],
              xs: 6,
              md: 4,
              path: "training.models.LSTM.Transferlearn_params.optimizer",
            },
            scheduler: {
              label: "Scheduler",
              type: "AutoComplete",
              placeholder: "Select scheduler",
              values: ["ReduceLROnPlateau", "CyclicLR"],
              xs: 6,
              md: 4,
              path: "training.models.LSTM.Transferlearn_params.scheduler",
            },

            feature_group_type: {
              label: "Feature Group Type",
              type: "AutoComplete",
              placeholder: "Select feature group type",
              values: ["feature_group_type1", "feature_group_type2"],
              xs: 12,
              md: 12,
              path: "training.models.LSTM.Transferlearn_params.feature_group_type",
            },
          },
        },
      },
    },

    // GRU Fields
    gru_multiprocessing: {
      label: "Multiprocessing",
      type: "Check",
      target: "config",
      path: "training.models.GRU.multiprocessing",
      direction: "column",
      xs: 12,
      md: 2,
    },
    gru_model_weights: {
      label: "Model Weights Filename",
      type: "TextInput",
      target: "config",
      placeholder: "Enter model weights filename",
      path: "training.models.GRU.model_weights_fname",
      showLabel: true,
      xs: 12,
      md: 6,
    },

    gru_feature_group: {
      label: "Select Feature Group to be created",
      isMultiSelect: true,
      type: "AutoComplete",
      target: "config",
      placeholder: "Type here....",
      path: "training.models.GRU.feature_groups",
      showLabel: true,
      xs: 12,
      md: 10,
      values: featuresArray,
    },

    gru_feature_group_type: {
      label: "Feature Group Type",
      type: "Check",
      target: "config",
      path: "training.models.GRU.feature_group_type",
      direction: "column",
      xs: 6,
      md: 2,
    },
    gru_scale: {
      label: "Scale Features",
      type: "Check",
      target: "config",
      path: "training.models.GRU.scale",
      direction: "column",
      xs: 6,
      md: 2,
    },

    gru_exclude_cols: {
      label: "Exclude Columns",
      type: "AutoComplete",
      target: "config",
      placeholder: "Select columns to exclude",
      path: "training.models.GRU.exclude_cols",
      showLabel: true,
      isMultiSelect: true,
      xs: 12,
      md: 8,
      values: taggedColumns,
    },
    gru_hyperparam_trials: {
      label: "Hyperparameter Trials",
      type: "Check",
      target: "config",
      path: "training.models.GRU.hyperparam_trials",
      direction: "column",
      xs: 6,
      md: 2,
    },
    gru_random_sample: {
      label: "Random Sample",
      type: "Check",
      target: "config",
      path: "training.models.GRU.random_sample",
      direction: "column",
      xs: 6,
      md: 2,
    },

    gru_trials: {
      label: "Number of Trials",
      type: "Counter",
      target: "config",
      placeholder: "Set number of trials",
      path: "training.models.GRU.trials",
      showLabel: true,
      maxRange: 100,
      minRange: 1,
      xs: 6,
      md: 8,
    },

    gru_trial_params: {
      label: "Trial Parameters",
      type: "custom",
      component: "TrialParamsManager",
      path: "training.models.GRU.trial_params",
      xs: 12,
      md: 12,
      modelType: "GRU",
    },

    gru_params: {
      label: "GRU Parameters",
      type: "nested",
      target: "config",
      path: "training.models.GRU.params",
      showLabel: true,
      xs: 12,
      md: 12,
      fields: {
        network_params: {
          label: "Network Parameters",
          type: "section",
          fields: {
            epochs: {
              label: "Epochs",
              type: "Counter",
              placeholder: "Set number of epochs",
              maxRange: 100,
              minRange: 1,
              xs: 6,
              md: 4,
              path: "training.models.GRU.params.network_params.epochs",
            },
            compression_factor: {
              label: "Compression Factor",
              type: "Counter",
              placeholder: "Set compression factor",
              maxRange: 100,
              minRange: 1,
              xs: 6,
              md: 4,
              path: "training.models.GRU.params.network_params.compression_factor",
            },
            max_embedding: {
              label: "Max Embedding",
              type: "Counter",
              placeholder: "Set max embedding",
              maxRange: 100,
              minRange: 1,
              xs: 6,
              md: 4,
              path: "training.models.GRU.params.network_params.max_embedding",
            },
          },
        },
        dataloader_params: {
          label: "Dataloader Parameters",
          type: "section",
          fields: {
            shuffle: {
              label: "Shuffle Data",
              type: "Check",
              xs: 6,
              md: 2,
              path: "training.models.GRU.params.dataloader_params.shuffle",
            },
            batch_size: {
              label: "Batch Size",
              type: "Counter",
              placeholder: "Set batch size",
              maxRange: 1000,
              minRange: 1,
              xs: 6,
              md: 5,
              path: "training.models.GRU.params.dataloader_params.batch_size",
            },

            num_workers: {
              label: "Number of Workers",
              type: "Counter",
              placeholder: "Set number of workers",
              maxRange: 16,
              minRange: 0,
              xs: 6,
              md: 5,
              path: "training.models.GRU.params.dataloader_params.num_workers",
            },
          },
        },
        GRU_params: {
          label: "GRU Specific Parameters",
          type: "section",
          fields: {
            gru_layers: {
              label: "GRU Layers",
              type: "Counter",
              placeholder: "Set number of GRU layers",
              maxRange: 10,
              minRange: 1,
              xs: 12,
              md: 12,
              path: "training.models.GRU.params.GRU_params.gru_layers",
            },
          },
        },
        optimizer_params: {
          label: "Optimizer Parameters",
          type: "section",
          fields: {
            RMSprop: {
              label: "RMSprop Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.GRU.params.optimizer_params.RMSprop.lr",
                },
                alpha: {
                  label: "Alpha",
                  type: "Counter",
                  placeholder: "Set alpha",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.GRU.params.optimizer_params.RMSprop.alpha",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 4,
                  path: "training.models.GRU.params.optimizer_params.RMSprop.weight_decay",
                },
              },
            },
            SGD: {
              label: "SGD Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.GRU.params.optimizer_params.SGD.lr",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.GRU.params.optimizer_params.SGD.weight_decay",
                },
              },
            },
            Adam: {
              label: "Adam Settings",
              type: "subsection",
              fields: {
                lr: {
                  label: "Learning Rate",
                  type: "Counter",
                  placeholder: "Set learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.GRU.params.optimizer_params.Adam.lr",
                },
                weight_decay: {
                  label: "Weight Decay",
                  type: "Counter",
                  placeholder: "Set weight decay",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.GRU.params.optimizer_params.Adam.weight_decay",
                },
              },
            },
          },
        },
        scheduler_params: {
          label: "Scheduler Parameters",
          type: "section",
          fields: {
            CyclicLR: {
              label: "CyclicLR Settings",
              type: "subsection",
              fields: {
                cycle_momentum: {
                  label: "Cycle Momentum",
                  type: "Check",
                  xs: 6,
                  md: 2,
                  path: "training.models.GRU.params.scheduler_params.CyclicLR.cycle_momentum",
                },
                base_lr: {
                  label: "Base Learning Rate",
                  type: "Counter",
                  placeholder: "Set base learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.GRU.params.scheduler_params.CyclicLR.base_lr",
                },
                max_lr: {
                  label: "Max Learning Rate",
                  type: "Counter",
                  placeholder: "Set max learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.GRU.params.scheduler_params.CyclicLR.max_lr",
                },
                step_size_up: {
                  label: "Step Size Up",
                  type: "Counter",
                  placeholder: "Set step size up",
                  maxRange: 100,
                  minRange: 1,
                  xs: 6,
                  md: 4,
                  path: "training.models.GRU.params.scheduler_params.CyclicLR.step_size_up",
                },
              },
            },
            ReduceLROnPlateau: {
              label: "ReduceLROnPlateau Settings",
              type: "subsection",
              fields: {
                mode: {
                  label: "Mode",
                  type: "AutoComplete",
                  placeholder: "Select mode",
                  values: ["min", "max"],
                  xs: 6,
                  md: 3,
                  path: "training.models.GRU.params.scheduler_params.ReduceLROnPlateau.mode",
                },
                factor: {
                  label: "Factor",
                  type: "Counter",
                  placeholder: "Set factor",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.GRU.params.scheduler_params.ReduceLROnPlateau.factor",
                },
                patience: {
                  label: "Patience",
                  type: "Counter",
                  placeholder: "Set patience",
                  maxRange: 100,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.GRU.params.scheduler_params.ReduceLROnPlateau.patience",
                },
                min_lr: {
                  label: "Minimum Learning Rate",
                  type: "Counter",
                  placeholder: "Set minimum learning rate",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 3,
                  path: "training.models.GRU.params.scheduler_params.ReduceLROnPlateau.min_lr",
                },
              },
            },
          },
        },
        SWA_params: {
          label: "SWA Parameters",
          type: "section",
          fields: {
            swa_start: {
              label: "SWA Start Epoch",
              type: "Counter",
              placeholder: "Set SWA start epoch",
              maxRange: 100,
              minRange: 1,
              xs: 6,
              md: 4,
              path: "training.models.GRU.params.SWA_params.swa_start",
            },
            swa_freq: {
              label: "SWA Frequency",
              type: "Counter",
              placeholder: "Set SWA frequency",
              maxRange: 100,
              minRange: 1,
              xs: 6,
              md: 4,
              path: "training.models.GRU.params.SWA_params.swa_freq",
            },
            swa_lr: {
              label: "SWA Learning Rate",
              type: "Counter",
              placeholder: "Set SWA learning rate",
              maxRange: 1,
              minRange: 0,
              xs: 6,
              md: 4,
              path: "training.models.GRU.params.SWA_params.swa_lr",
            },
          },
        },
        callback_params: {
          label: "Callback Parameters",
          type: "section",
          fields: {
            earlystopping: {
              label: "Early Stopping",
              type: "subsection",
              fields: {
                patience: {
                  label: "Patience",
                  type: "Counter",
                  placeholder: "Set early stopping patience",
                  maxRange: 100,
                  minRange: 0,
                  xs: 12,
                  md: 12,
                  path: "training.models.GRU.params.callback_params.earlystopping.patience",
                },
              },
            },
          },
        },
        regularization: {
          label: "Regularization",
          type: "section",
          fields: {
            l2_norm: {
              label: "Use L2 Normalization",
              type: "Check",
              xs: 6,
              md: 4,
              path: "training.models.GRU.params.regularization.l2_norm",
            },
            reg_param: {
              label: "Regularization Parameters",
              type: "subsection",
              fields: {
                reg_loss: {
                  label: "Regularization Loss",
                  type: "AutoComplete",
                  placeholder: "Select regularization loss",
                  values: [, null],
                  xs: 6,
                  md: 6,
                  path: "training.models.GRU.params.regularization.reg_param.reg_loss",
                },
                lmbda: {
                  label: "Lambda",
                  type: "Counter",
                  placeholder: "Set lambda value",
                  maxRange: 1,
                  minRange: 0,
                  xs: 6,
                  md: 6,
                  path: "training.models.GRU.params.regularization.reg_param.lmbda",
                },
              },
            },
          },
        },
        parameter_averaging: {
          label: "Parameter Averaging",
          type: "section",
          fields: {
            window: {
              label: "Averaging Window",
              type: "Counter",
              placeholder: "Set averaging window",
              maxRange: 100,
              minRange: 1,
              xs: 12,
              md: 12,
              path: "training.models.GRU.params.parameter_averaging.window",
            },
          },
        },
        Tlearn_params: {
          label: "Transfer Learning Parameters",
          type: "section",
          fields: {
            specific_FC_layers: {
              label: "Specific FC Layers",
              type: "Counter",
              placeholder: "Set number of FC layers",
              maxRange: 100,
              minRange: 1,
              xs: 12,
              md: 12,
              path: "training.models.GRU.params.Tlearn_params.specific_FC_layers",
            },
          },
        },
      },
    },

    week_active_days: {
      label: "Week Active Days",
      type: "Counter",
      target: "config",
      placeholder: "Set number of active days",
      path: "data.week_active_days",
      showLabel: true,
      maxRange: 7,
      minRange: 1,
      xs: 12,
      md: 6,
    },
    date_offset: {
      label: "Date Offset",
      type: "Counter",
      target: "config",
      placeholder: "Set date offset",
      path: "data.date_offset",
      showLabel: true,
      maxRange: 365,
      minRange: 0,
      xs: 12,
      md: 6,
    },
  };
};
