export const allTags = {
  timestamp_column: {
    label: "Date",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.timestamp_column",
    infoTooltip: "Select the date column in sales data. (Mandatory)",
    docLink: "user-guide/experiment-self-serve/demand-planning/add-data",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  target_column: {
    label: "Target",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.target_column",
    showLabel: true,
    infoTooltip: "Select the column to predict. (Mandatory)",
    docLink: "user-guide/experiment-self-serve/demand-planning/add-data",
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: false,
    default_fillNa_option: "0",
    fillNa_disabled: false,
    in_aggregation: true,
  },
  id_column: {
    label: "Image ID",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.ts_id_column",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  date_format: {
    label: "Date Format",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.date_format",
    infoTooltip: "Select the date format as per the sales data. (Mandatory)",
    docLink: "user-guide/experiment-self-serve/demand-planning/add-data",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  regressor_columns: {
    label: "Additional Attributes",
    isMultiSelect: true,
    inputType: "AutoComplete",
    path: "field_tags.regressor_columns",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  ts_id_columns: {
    label: "Granularity",
    isMultiSelect: true,
    inputType: "AutoComplete",
    path: "field_tags.ts_id_columns",
    showLabel: true,
    infoTooltip: "Set of granular features which defines the level at which forecasts need to done. (Mandatory)",
    docLink: "user-guide/experiment-self-serve/demand-planning/add-data",
    xs: 12,
    md: 6,
  },
  driver_columns: {
    label: "Driver",
    isMultiSelect: true,
    inputType: "AutoComplete",
    path: "field_tags.driver_columns",
    showLabel: true,
    infoTooltip: "Features which can impact / drive forecasts. (Optional)",
    docLink: "user-guide/experiment-self-serve/demand-planning/add-data",
    xs: 12,
    md: 6,
    default_aggregate_option: "mean",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: true,
  },
  optimization_column: {
    label: "Optimization Field",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.optimization_column",
    showLabel: true,
    infoTooltip: "Feature which needs to be optimised. (Optional)",
    docLink: "user-guide/experiment-self-serve/demand-planning/add-data",
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: true,
  },
  inventory_column: {
    label: "Inventory",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.inventory_column",
    showLabel: true,
    infoTooltip: "Field which has stock on Hand (SOH) value. (Mandatory).",
    docLink: "user-guide/experiment-self-serve/inventory-planning/add-inventory-dataset",
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: true,
    default_fillNa_option: "None",
    fillNa_disabled: true,
    in_aggregation: false,
  },
  dimensions: {
    label: "Other Interesting Dimensions",
    showLabel: true,
    xs: 12,
    md: 6,
    isMultiSelect: true,
    inputType: "AutoComplete",
    path: "field_tags.dimensions",
    showLabel: true,
    infoTooltip: " Fields which you want to be added in the dashboard. Please note that the granularity of these features should be higher than model granularity. (Optional)",
    docLink: "user-guide/experiment-self-serve/demand-planning/add-data",
    xs: 12,
    md: 6,
    default_aggregate_option: "max",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },
  return_qty_column: {
    label: "Returns",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.return_qty_column",
    showLabel: true,
    infoTooltip: "Field which has returns quantity. (Optional)",
    docLink: "user-guide/experiment-self-serve/demand-planning/add-data",
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: true,
    default_fillNa_option: "None",
    fillNa_disabled: true,
    in_aggregation: false,
  },
  replenishment_columns: {
    label: "Replenishment Constraints",
    isMultiSelect: true,
    inputType: "AutoComplete",
    path: "field_tags.replenishment_columns",
    showLabel: true,
    infoTooltip: "Select columns which consist of replenishment constraints data. (Optional)",
    docLink: "user-guide/experiment-self-serve/inventory-planning/add-inventory-dataset",
    xs: 12,
    md: 6,
    default_aggregate_option: "max",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },


 

    


    supply_item_master: {
    label: "Supply Item Master?",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.supply_item_master",
    showLabel: true,
    
    xs: 12,
    md: 2.5,
    default_aggregate_option: "max",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },

   intransit: {
    label: "In Transit",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.intransit",
    showLabel: true,
    
    xs: 12,
    md: 9.5,
    default_aggregate_option: "max",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },
  batch_column: {
    label: "Batch ID",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.batch_column",
    showLabel: true,
    infoTooltip: "Select column with Batch Id, if POs are delivered in tranches/batches. (Optional)",
    docLink: "user-guide/experiment-self-serve/inventory-planning/add-inventory-dataset",
    xs: 12,
    md: 6,
  },
  store_number: {
    label: "Store ID",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.store_number",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  floor: {
    label: "Floor Number",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.floor",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  mod: {
    label: "Mod ID",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.mod",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  h_shelf: {
    label: "Horizontal Shelf",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.h_shelf",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  v_shelf: {
    label: "Vertical Shelf",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.v_shelf",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  store__category: {
    label: "Category",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.store__category",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  store__dimensions__width: {
    label: "Shelf Width",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.store__dimensions__width",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  store__dimensions__height: {
    label: "Shelf Height",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.store__dimensions__height",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  store__dimensions__depth: {
    label: "Shelf Depth",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.store__dimensions__depth",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  store__facing_constraint__min: {
    label: "Min Facings per SKU",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.store__facing_constraint__min",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  store__facing_constraint__max: {
    label: "Max Facings per SKU",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.store__facing_constraint__max",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  product_id: {
    label: "Product ID",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.product_id",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  product__brand: {
    label: "Brand",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.product__brand",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  product__category: {
    label: "Category",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.product__category",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  cost_price: {
    label: "Cost Price",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.cost_price",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  selling_price: {
    label: "Selling Price",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.selling_price",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  margin: {
    label: "Margin %",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.margin",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  product__dimensions__width: {
    label: "Product Width(cms)",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.product__dimensions__width",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  product__dimensions__height: {
    label: "Product Height(cms)",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.product__dimensions__height",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  product__dimensions__depth: {
    label: "Product Depth(cms)",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.product__dimensions__depth",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  product__facing_constraint__min: {
    label: "Min Facings Product",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.product__facing_constraint__min",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  product__facing_constraint__max: {
    label: "Max Facings Product",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.product__facing_constraint__max",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  inventory_column_bom: {
    label: "Raw Material Inventory",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.inventory_column_bom",
    showLabel: true,
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: true,
    default_fillNa_option: "None",
    fillNa_disabled: true,
    in_aggregation: false,
  },
  tg_forecast: {
    label: "TG Forecast",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.tg_forecast",
    showLabel: true,
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },
  sales_forecast: {
    label: "Sales Forecast",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.sales_forecast",
    showLabel: true,
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },
  marketing_forecast: {
    label: "Marketing Forecast",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.marketing_forecast",
    showLabel: true,
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },
  ops_forecast: {
    label: "Ops Forecast",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.ops_forecast",
    showLabel: true,
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },
  consensus_forecast: {
    label: "Consensus Forecast",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.consensus_forecast",
    showLabel: true,
    xs: 12,
    md: 6,
    default_aggregate_option: "sum",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },
  comments: {
    label: "Comments",
    isMultiSelect: true,
    inputType: "AutoComplete",
    path: "field_tags.comments",
    showLabel: true,
    xs: 12,
    md: 6,
    default_aggregate_option: "max",
    aggregate_disabled: false,
    default_fillNa_option: "None",
    fillNa_disabled: false,
    in_aggregation: false,
  },
  transition_data_old_item_column: {
    label: "Old Item",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.transition_data_old_item_column",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  transition_data_new_item_column: {
    label: "New Item",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.transition_data_new_item_column",
    showLabel: true,
    xs: 12,
    md: 6,
  },
  sales_data_item_column: {
    label: "Sales Data Item",
    isMultiSelect: false,
    inputType: "AutoComplete",
    path: "field_tags.sales_data_item_column",
    showLabel: true,
    xs: 12,
    md: 6,
  },
};
