import React from "react";
import {
  Button,
  Typography,
  Box,
  Stack,

} from "@mui/material";
// import { ThemeContext } from "../../../../theme/config/ThemeContext";
import FormControl from "@mui/material/FormControl";
import FormGroup from "@mui/material/FormGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";

const btnText = {
  fontFamily: "Inter",
  fontSize: "14px",
  fontWeight: 600,
  lineHeight: "20px",
  textAlign: "left",
  color: "#344054",
  textTransform: "none",
};

const textLgMedium = {
  fontFamily: "Inter",
  fontSize: "18px",
  fontWeight: 500,
  lineHeight: "28px",
  textAlign: "left",
  color: "#101828",
};

const textSubLine = {
  fontFamily: "Inter",
  fontSize: "14px",
  fontWeight: 400,
  lineHeight: "20px",
  textAlign: "left",
  color: "#475467",
};

const ModelMetric = () => {
  const [state, setState] = React.useState({
    gilad: true,
    jason: false,
    antoine: false,
  });

  const handleChange = (event) => {
    setState({
      ...state,
      [event.target.name]: event.target.checked,
    });
  };

  // const { gilad, jason, antoine } = state;
  // const error = [gilad, jason, antoine].filter((v) => v).length !== 2;
  // const { theme } = useContext(ThemeContext);

  return (
    <div>
      <Box>
        <Box
          sx={{
            padding: "20px 24px 19px 24px",
            display: "flex",
            flexDirextion: "row",
            justifyContent: "space-between",
          }}
        >
          <Stack>
            <Typography sx={textLgMedium}>Download Outputs</Typography>
            <Typography sx={textSubLine}>
              Download different Outputs generated by the Experiment
            </Typography>
          </Stack>
          <Button
            size="medium"
            sx={{
              border: "1px solid #D0D5DD",
              borderRadius: "8px",
              padding: "10px 16px",
              maxHeight: "40px",
              // box-shadow: 0px 1px 2px 0px rgba(16, 24, 40, 0.05);
            }}
          >
            <Stack direction="row" spacing={1}>
              <Typography sx={btnText}>Select Outputs</Typography>
            </Stack>
          </Button>
        </Box>
        <Box
          sx={{
            padding: "20px 24px 19px 24px",
            display: "flex",
            flexDirextion: "row",
            justifyContent: "space-between",
          }}
        >
          <Stack>
            <Typography sx={textLgMedium}>Export Object</Typography>
            <Typography sx={textSubLine}>
              Stage this experiment output to be exported to the predefined
              external connector.
              <br />
              Clicking this will replace any previously staged experiment
              output.
            </Typography>
          </Stack>

          <Stack alignItems={"flex-start"}>
            <Typography sx={textLgMedium}>Select outputs to stage</Typography>
            <FormControl component="fieldset" variant="standard">
              <FormGroup>
                <Stack direction="row">
                  <FormControlLabel
                    control={
                      <Checkbox
                        onChange={handleChange}
                        sx={{
                          color: "#D0D5DD",
                          width: "20px",
                          height: "20px",
                          padding: 2,
                          "&.Mui-checked": {
                            color: "#0C66E4",
                          },
                        }}
                      />
                    }
                    label="forecast "
                    sx={{
                      color: "#344054",

                      lineHeight: "1.5rem",

                      "& .MuiFormControlLabel-label": {
                        fontFamily: "Inter",
                        fontSize: "1rem",
                        fontWeight: "500",
                      },
                    }}
                  />
                  <FormControlLabel
                    control={
                      <Checkbox
                        onChange={handleChange}
                        sx={{
                          color: "#D0D5DD",
                          width: "20px",
                          height: "20px",
                          padding: 2,
                          "&.Mui-checked": {
                            color: "#0C66E4",
                          },
                        }}
                      />
                    }
                    label="Replacement_optimization "
                    sx={{
                      color: "#344054",

                      lineHeight: "1.5rem",

                      "& .MuiFormControlLabel-label": {
                        fontFamily: "Inter",
                        fontSize: "1rem",
                        fontWeight: "500",
                      },
                    }}
                  />
                </Stack>
              </FormGroup>
            </FormControl>
          </Stack>
          <Button
            size="medium"
            sx={{
              border: "1px solid #D0D5DD",
              borderRadius: "8px",
              padding: "10px 16px",
              maxHeight: "40px",
            }}
          >
            <Stack direction="row" spacing={1}>
              <Typography sx={btnText}>Stage Exports</Typography>
            </Stack>
          </Button>
        </Box>
        <Box
          sx={{
            padding: "20px 24px 19px 24px",
            display: "flex",
            flexDirextion: "row",
            justifyContent: "space-between",
          }}
        >
          <Stack>
            <Typography sx={textLgMedium}>Run Inference</Typography>
            <Typography sx={textSubLine}>
              Upload required objects and run model inference on new data.
            </Typography>
          </Stack>
          <Button
            size="medium"
            sx={{
              border: "1px solid #D0D5DD",
              borderRadius: "8px",
              padding: "10px 16px",
              maxHeight: "40px",
            }}
          >
            <Stack direction="row" spacing={1}>
              <Typography sx={btnText}>Run Inference</Typography>
            </Stack>
          </Button>
        </Box>
      </Box>
    </div>
  );
};

export default ModelMetric;
