import { dateFormats } from "../Formating/dateFormating";

export const allContextFields = () => {
  return {
    activity_end_date: {
      component: "DatePicker",
      target: "context",
      is_enabled: true,
      label: "Select a date:",
      path: "etl.activity_end_date",
      showLabel: true,
      required: false,
      xs: 6,
      md: 4,
    },
    history: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your history days",
      label: "History  Since (Days)",
      maxRange: 5000,
      minRange: 0,
      path: "etl.history",
      xs: 6,
      md: 4,
    },
    activity_period: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your activity days",
      label: "Active Since Days",
      maxRange: 5000,
      minRange: 0,
      path: "etl.activity_period",
      xs: 6,
      md: 4,
    },
    frequency: {
      component: "AutoComplete",
      conflictCheck: false,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set frequency",
      label: "Time Granularity",
      isMultiSelect: false,
      values: ["W", "M", "Q", "D", "Y", "H", "30T", "15T", "10T", "5T"],
      dateFormat: false,
      valuesDict: {
        W: "Weekly",
        M: "Monthly",
        Q: "Quarterly",
        D: "Daily",
        Y: "Yearly",
        H: "Hourly",
        "30T": "30 minute",
        "15T": "15 minute",
        "10T": "10 minute",
        "5T": "5 minute",
      },
      path: "data.frequency",
      xs: 12,
      md: 4,
    },
    forecast_horizon: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your forecast horizon",
      label: "Forecast Horizon",
      maxRange: 5000,
      minRange: 0,
      path: "data.forecast_horizon",
      xs: 12,
      md: 4,
    },
    validation_horizon: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your validation horizon",
      label: "Validation Horizon",
      maxRange: 5000,
      minRange: 0,
      path: "data.validation_horizon",
      xs: 12,
      md: 4,
    },
    historical_reference_date: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Historical Reference Date?",
      direction: "column",
      path: "scenario_plan.historical_reference_date",
      xs: 12,
      md: 3,
    },

    filter_target_gt_zero: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Filter for Target greater than 0",
      direction: "column",
      path: "data.filter_target_gt_zero",
      xs: 12,
      md: 3,
    },

    ts_id_columns: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select granularity for forecasting",
      label: "Select Granularity for Forecasting",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "data.ts_id_columns",
      xs: 12,
      md: 6,
    },
    ts_id_columns_disagg: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select granularity for disaggregation",
      label: "Select Granularity for Disaggregation",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "data.ts_id_columns_disagg",
      xs: 12,
      md: 6,
    },

    Oscillator_based_on_disaggregation: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Oscillator based on Disaggregation?",
      direction: "column",
      path: "scenario_plan.inventory_constraints.Oscillator_based_on_disaggregation",
      xs: 12,
      md: 3,
    },
    ml_based_disaggregation: {
      component: "AutoComplete",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select granularity for inventory optimization",
      label: "Disaggregation Type",
      isMultiSelect: false,
      values: [
        "ml_based_disaggregation",
        "proportion_based_disaggregation",
        "simple_disaggregation",
      ],
      valuesDict: {
        ml_based_disaggregation: "ML Based",
        proportion_based_disaggregation: "Proportion Based",
        simple_disaggregation: "Simple Disaggregation",
      },
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.disaggregation_type",
      xs: 12,
      md: 9,
    },

    multiprocessing_disaggregation: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Enable Multiprocessing for Disaggregation?",
      direction: "column",
      path: "scenario_plan.multiprocessing_disaggregation",
      xs: 12,
      md: 3,
    },

    disaggregation_distribution_key: {
      component: "AutoComplete",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select disaggregation distribution key columns",
      label: "Disaggregation Distribution Key",
      isMultiSelect: true,
      values: "taggedColumns", // This should be populated with available columns

      dateFormat: false,
      path: "scenario_plan.inventory_constraints.disaggregation_distribution_key",
      xs: 12,
      md: 9,
    },

    simple_disaggregation_forecasting_heading_1: {
      component: "heading",
      title: "Simple Disaggregation",
      xs: 12,
      md: 12,
    },

    ts_id_columns_simple_disaggr: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Simple Disaggregated granularity",
      label: "Simple Disaggregated Granularity",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.simple_disaggr.ts_id_columns_simple_disaggr",
      xs: 12,
      md: 12,
    },

    bundle_mapping_granularity: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select bundle mapping granularity",
      label: "Bundle Mapping Granularity",
      isMultiSelect: false,
      values: "taggedColumns", // You can later expand options if needed
      dateFormat: false,
      path: "scenario_plan.simple_disaggr.bundle_mapping_granularity",
      xs: 12,
      md: 6,
    },

    bundle_forecast_granularity: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select bundle forecast granularity",
      label: "Bundle Forecast Granularity",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.simple_disaggr.bundle_forecast_granularity",
      xs: 12,
      md: 6,
    },

    simple_mapping: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select simple mapping",
      label: "Simple Mapping",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.simple_disaggr.simple_mapping",
      xs: 12,
      md: 6,
    },

    simple_disaggregation_quantity: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select quantity field",
      label: "Simple Disaggregation Quantity",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.simple_disaggr.simple_disaggregation_quantity",
      xs: 12,
      md: 6,
    },

    inventory_optimisation_granularity: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select granularity for inventory optimization",
      label: "Select Granularity for Inventory Optimization",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.inventory_optimisation_granularity",
      xs: 12,
      md: 6,
    },
    inventory_planning_frequency: {
      component: "AutoComplete",
      conflictCheck: false,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set frequency",
      label: "Time Granularity",
      isMultiSelect: false,
      values: ["W", "M", "Q", "D", "Y", "H", "30T", "15T", "10T", "5T"],
      dateFormat: false,
      valuesDict: {
        W: "Weekly",
        M: "Monthly",
        Q: "Quarterly",
        D: "Daily",
        Y: "Yearly",
        H: "Hourly",
        "30T": "30 minute",
        "15T": "15 minute",
        "10T": "10 minute",
        "5T": "5 minute",
      },
      path: "scenario_plan.inventory_constraints.inventory_planning_frequency",
      xs: 12,
      md: 6,
    },

    multiprocessing_inventory: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Enable Multiprocessing for Inventory?",
      direction: "column",
      path: "scenario_plan.multiprocessing_inventory",
      xs: 12,
      md: 3,
    },
    inventory_distribution_key: {
      component: "AutoComplete",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select inventory distribution key columns",
      label: "Inventory Distribution Key",
      isMultiSelect: true,
      values: "taggedColumns", // This should be populated with available columns

      dateFormat: false,
      path: "scenario_plan.inventory_constraints.inventory_distribution_key",
      xs: 12,
      md: 9,
    },
    adjust_reorder_basis_moving_forecast: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Adjust Reorder Basis Moving Forecast?",
      direction: "column",
      path: "scenario_plan.inventory_constraints.adjust_reorder_basis_moving_forecast",
      xs: 12,
      md: 6,
    },
    add_non_sellable_inventory: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Add non sellable inventory?",
      direction: "column",
      path: "scenario_plan.inventory_constraints.add_non_sellable_inventory",
      xs: 12,
      md: 6,
    },

    disaggregate_inventory_metrics: {
      component: "AutoComplete",
      conflictCheck: false,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Disaggregate inventory metrics",
      label: "Disaggregate inventory metrics",
      isMultiSelect: true,
      values: [
        "Script(return config?.data?.inventory_column ?? [];)",
        "Script(return config?.etl?.loaded_datasets?.inventory?.[0]?.field_tags?.replenishment_columns ?? [];)",
        "running_purchase_order",
        "MOQ",
      ],
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.disaggregate_inventory_metrics",
      xs: 12,
      md: 6,
    },

    disaggregate_inventory_metrics_granularity: {
      component: "AutoComplete",
      conflictCheck: false,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Disaggregate inventory metrics granularity",
      label: "Disaggregate inventory metrics granularity",
      isMultiSelect: true,
      values: [
        "Script(return config?.data?.inventory_column ?? [];)",
        "Script(return config?.etl?.loaded_datasets?.inventory?.[0]?.field_tags?.replenishment_columns ?? [];)",
        "running_purchase_order",
        "MOQ",
      ],
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.disaggregate_inventory_metrics_granularity",
      xs: 12,
      md: 6,
    },

    disaggregate_inventory_metrics_history: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Disaggregate inventory metrics history",
      label: "Disaggregate inventory metrics history",
      maxRange: 1000,
      minRange: 0,
      path: "scenario_plan.inventory_constraints.disaggregate_inventory_metrics_history",
      xs: 12,
      md: 6,
    },

    lead_time_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select lead time column",
      label: "Select lead time column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.lead_time_col",
      xs: 12,
      md: 6,
    },
    lead_time: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your lead time",
      label: "Lead Time (Days)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.inventory_constraints.lead_time",
      xs: 12,
      md: 6,
    },
    current_safety_stock_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select current safety stock column",
      label: "Select current safety stock column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.current_safety_stock_col",
      xs: 12,
      md: 4,
    },
    safety_stock_days_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select safety stock column",
      label: "Select Max Safety stock column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.safety_stock_days_col",
      xs: 12,
      md: 4,
    },
    safety_stock_days: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your safety stock",
      label: "Safety Stock (Days)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.inventory_constraints.safety_stock_days",
      xs: 12,
      md: 4,
    },
    Ideal_DOI_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Ideal DOI column",
      label: "Select Ideal DOI column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.Ideal_DOI_col",
      xs: 12,
      md: 6,
    },
    Ideal_DOI: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your Ideal DOI",
      label: "Ideal DOI (Days)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.inventory_constraints.Ideal_DOI",
      xs: 12,
      md: 6,
    },

    service_level_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select service level column",
      label: "Select Service Level column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.service_level_col",
      xs: 12,
      md: 6,
    },
    service_level: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your Service Level",
      label: "Service Level (%)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.inventory_constraints.service_level",
      xs: 12,
      md: 6,
    },
    minimum_order_qty_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select MOQ column",
      label: "Select MOQ column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.minimum_order_qty_col",
      xs: 12,
      md: 6,
    },
    minimum_order_qty: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your MOQ value",
      label: "Minimum Order Quantity (MOQ) Value",
      maxRange: 20000,
      minRange: 0,
      path: "scenario_plan.inventory_constraints.minimum_order_qty",
      xs: 12,
      md: 6,
    },
    running_purchase_order: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select running PO column",
      label: "Select Running Purchase Order (PO) column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.running_purchase_order",
      xs: 12,
      md: 4,
    },
    open_purchase_order: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select open PO column",
      label: "Select Open Purchase Order (PO) column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.open_purchase_order",
      xs: 12,
      md: 4,
    },
    days_to_running_po: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select days to running PO column",
      label: "Select Days to Running PO column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.days_to_running_po",
      xs: 12,
      md: 4,
    },
    enable_stock_transfer: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Enable stock Transfer?",
      direction: "row",
      path: "scenario_plan.inventory_constraints.enable_stock_transfer",
      xs: 12,
      md: 4,
    },
    stock_transfer_level: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select product level of stock transfer",
      label: "Select Product Level of stock transfer",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.stock_transfer_level",
      xs: 12,
      md: 4,
    },

    stock_transfer_dimension: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Product Dimensions",
      label: "Select Product Dimensions",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.item_id_dimensions",
      xs: 12,
      md: 4,
    },

    stock_transfer_facility: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select product level of stock transfer",
      label: "Select Facility Level of stock transfer",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.stock_transfer_facility",
      xs: 12,
      md: 6,
    },
    stock_transfer_facility_dimension: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Facility Dimensions",
      label: "Select Facility Dimensions",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.facility_dimensions",
      xs: 12,
      md: 6,
    },

    stock_transfer_zone: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder:
        " Select Zone Priority Order across which stock transfer will happen",
      label:
        "Select Zone Priority Order across which stock transfer will happen",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.stock_transfer_zone",
      xs: 12,
      md: 6,
    },

    stock_transfer_zone_dimensions: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select zone Dimensions",
      label: "Select Zone Dimensions",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.zone_dimensions",
      xs: 12,
      md: 6,
    },

    unconstriant_stock_transfer: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question:
        "Allow unconstraint stock transfer after priority zone transfers",
      direction: "column",
      path: "scenario_plan.inventory_constraints.unconstriant_stock_transfer",
      xs: 12,
      md: 6,
    },

    stock_transfer_adjusted_reorder: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Optimize Reorder with stock transfer",
      direction: "column",
      path: "scenario_plan.inventory_constraints.stock_transfer_adjusted_reorder",
      xs: 12,
      md: 6,
    },

    batch_column: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select BatchID column",
      label: "BatchID Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "data.batch_column",
      xs: 12,
      md: 4,
    },
    expiry_date: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select expiry date Column",
      label: "Expiry Date Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "data.expiry_date",
      xs: 12,
      md: 4,
    },
    expiry_date_format: {
      component: "AutoComplete",
      conflictCheck: false,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select expiry date format",
      label: "Expiry Date Format",
      isMultiSelect: false,
      values: dateFormats,
      path: "data.expiry_date_format",
      dateFormat: true,
      xs: 12,
      md: 4,
    },
    tolerance_level_days_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select tolerance level column",
      label: "Select Tolerance level(in Days) column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.tolerance_level_days_col",
      xs: 12,
      md: 6,
    },
    tolerance_level_days: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your tolerance level",
      label: "Tolerance level(in Days)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.inventory_constraints.tolerance_level_days",
      xs: 12,
      md: 6,
    },
    enable_network_optimization: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Enable Network Optimization?",
      direction: "row",
      path: "scenario_plan.inventory_constraints.enable_network_optimization",
      xs: 12,
      md: 6,
    },
    parent_warehouse_node_buffer: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Parent Warehouse Node Buffer?",
      direction: "row",
      path: "scenario_plan.inventory_constraints.parent_warehouse_node_buffer",
      xs: 12,
      md: 6,
    },
    item_node: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select item node",
      label: "Select Item Node",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.item_node",
      xs: 12,
      md: 6,
    },
    warehouse_node: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select warehouse node",
      label: "Select Warehouse Node",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.warehouse_node",
      xs: 12,
      md: 6,
    },
    fulfillment_node: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select fulfillment node",
      label: "Select Fulfillment Node",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.fulfillment_node",
      xs: 12,
      md: 6,
    },
    network_sequence: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select network sequence column",
      label: "Select Network Sequence column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.network_sequence",
      xs: 12,
      md: 6,
    },
    rewrite_forecast: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select forecast rewrite column",
      label: "Forecast Rewrite Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.forecast_rewrite",
      xs: 12,
      md: 6,
    },
    total_demand: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select total demand column",
      label: "Total Demand Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.total_demand",
      xs: 12,
      md: 6,
    },
    inventory_pivot_data: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Custom Pivot View for Inventory?",
      direction: "column",
      path: "scenario_plan.inventory_constraints.inventory_pivot_data",
      xs: 12,
      md: 3,
    },
    round_off_reorder: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Round-Off Reorder Units?",
      direction: "column",
      path: "scenario_plan.inventory_constraints.round_off_reorder",
      xs: 12,
      md: 3,
    },
    round_off_reorder_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select round off reorder column",
      label: "Select Round Off Reorder Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.round_off_reorder_col",
      xs: 12,
      md: 4.5,
    },
    row_dim: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select row dim in pivot",
      label: "Select Row Dim in Pivot",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.row_dim",
      xs: 12,
      md: 3,
    },
    column_dim: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select column dim in pivot",
      label: "Select Column Dim in Pivot",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.column_dim",
      xs: 12,
      md: 3,
    },
    pivot_features: {
      component: "AutoComplete",
      conflictCheck: false,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select metrics to display in pivot",
      label: "Select Metrics to display in Pivot",
      isMultiSelect: true,
      values: [
        "sales_last7days",
        "sales_last30days",
        "sales_last60days",
        "sales_last90days",
        "Sales_Per_Day",
        "Forecast_Per_Day",
        "Stock_On_Hand",
        "DOI_Current_Stock",
        "in_transit",
        "DOI",
        "safety_stock",
        "Reorder_now",
        "Excess_Stock",
        "Potential_Sales_Loss",
      ],
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.pivot_features",
      xs: 12,
      md: 3,
    },
    round_off_by: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "round off by...",
      label: "Round-Off By",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.inventory_constraints.round_off_by",
      xs: 12,
      md: 4.5,
    },

    finished_good_column_mapping_granularity: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Finished Good Mapping Column",
      label: "Select Finished Good Mapping Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.finished_good_column_mapping_granularity",
      xs: 12,
      md: 6,
    },
    plant_column_mapping_granularity: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Plant Mapping Column",
      label: "Select Plant Mapping Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.plant_column_mapping_granularity",
      xs: 12,
      md: 6,
    },
    finished_good_column_forecast_granularity: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Finished Good Forecast Column",
      label: "Select Finished Good Forecast Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.finished_good_column_forecast_granularity",
      xs: 12,
      md: 6,
    },
    plant_column_forecast_granularity: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select plant forecast column",
      label: "Select Plant Forecast Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.plant_column_forecast_granularity",
      xs: 12,
      md: 6,
    },
    raw_material_column_mapping: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select raw material mapping column",
      label: "Select Raw Material Mapping Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.raw_material_column_mapping",
      xs: 12,
      md: 6,
    },
    raw_material_qty: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select raw Material Quantity Column",
      label: "Select Raw Material Quantity Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials..raw_material_qty",
      xs: 12,
      md: 6,
    },

    bom_lead_time_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select lead time column",
      label: "Select lead time column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.lead_time_col",
      xs: 12,
      md: 6,
    },
    bom_lead_time: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your lead time",
      label: "Lead Time (Days)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.bill_of_materials.lead_time",
      xs: 12,
      md: 6,
    },
    bom_safety_stock_days_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select safety stock column",
      label: "Select Max Safety stock column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.safety_stock_days_col",
      xs: 12,
      md: 6,
    },
    bom_safety_stock_days: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your safety stock",
      label: "Safety Stock (Days)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.bill_of_materials.safety_stock_days",
      xs: 12,
      md: 6,
    },
    bom_Ideal_DOI_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Ideal DOI column",
      label: "Select Ideal DOI column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.Ideal_DOI_col",
      xs: 12,
      md: 6,
    },
    bom_Ideal_DOI: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your Ideal DOI",
      label: "Ideal DOI (Days)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.bill_of_materials.Ideal_DOI",
      xs: 12,
      md: 6,
    },
    bom_service_level_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select service level column",
      label: "Select Service Level column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.service_level_col",
      xs: 12,
      md: 6,
    },
    bom_service_level: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your Service Level",
      label: "Service Level (%)",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.bill_of_materials.service_level",
      xs: 12,
      md: 6,
    },
    bom_minimum_order_qty_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select MOQ column",
      label: "Select MOQ column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.minimum_order_qty_col",
      xs: 12,
      md: 6,
    },
    bom_minimum_order_qty: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your MOQ value",
      label: "Minimum Order Quantity (MOQ) Value",
      maxRange: 20000,
      minRange: 0,
      path: "scenario_plan.bill_of_materials.minimum_order_qty",
      xs: 12,
      md: 6,
    },
    bom_running_purchase_order: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select running PO column",
      label: "Select Running Purchase Order (PO) column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.running_purchase_order",
      xs: 12,
      md: 6,
    },

    bom_days_to_running_po: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select days to running PO column",
      label: "Select Days to Running PO column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.bill_of_materials.days_to_running_po",
      xs: 12,
      md: 12,
    },
    currency: {
      component: "AutoComplete",
      is_enabled:
        "Script(return config.data.currency !== 'None' && config.data.currency !== null;)",
      conflictCheck: false,
      target: "context",
      showLabel: true,
      placeholder: "Select currency",
      label: "Select Currency",
      isMultiSelect: false,
      values: ["USD", "INR"],
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.currency",
      xs: 12,
      md: 6,
    },

    budget: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select Budget Columns",
      label: "Select Budget Columns",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.budget",
      xs: 12,
      md: 6,
    },

    cost: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select cost column",
      label: "Select cost column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.cost",
      xs: 12,
      md: 6,
    },
    price: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select price column",
      label: "Select price column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.price",
      xs: 12,
      md: 6,
    },
    MRP: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select MRP column",
      label: "Select MRP (price rewrite) column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.MRP",
      xs: 12,
      md: 6,
    },
    Objective: {
      component: "AutoComplete",
      conflictCheck: false,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select objective",
      label: "Select Objective",
      isMultiSelect: false,
      values: ["Revenue", "Margin"],
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.Objective",
      xs: 12,
      md: 6,
    },
    Revenue_target_Percent: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set revenue target",
      label: "Select Revenue Target Percent",
      maxRange: 100,
      minRange: -100,
      path: "scenario_plan.pricing_constraints.Revenue_target_Percent",
      xs: 12,
      md: 6,
    },
    Margin_Target_Percent: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set margin target",
      label: "Select Margin Target Percent",
      maxRange: 100,
      minRange: -100,
      path: "scenario_plan.pricing_constraints.Margin_Target_Percent",
      xs: 12,
      md: 6,
    },
    Min_Price_Change: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set minimum price change Percent",
      label: "Select minimum price change Percent",
      maxRange: 100,
      minRange: -100,
      path: "scenario_plan.pricing_constraints.Min_Price_Change",
      xs: 12,
      md: 6,
    },
    Max_Price_Change: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set maximum price change percent",
      label: "Select maximum price change Percent",
      maxRange: 100,
      minRange: -100,
      path: "scenario_plan.pricing_constraints.Max_Price_Change",
      xs: 12,
      md: 6,
    },

    margin_assumption: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set margin assumption",
      label: "Select margin assumption",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.pricing_constraints.margin_assumption",
      xs: 12,
      md: 6,
    },
    Iterations: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set number of iterations",
      label: "Select number of Iterations",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.pricing_constraints.Iterations",
      xs: 12,
      md: 6,
    },
    mkd_margin_perc_min: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set minimum margin cut factor for markdown",
      label: "Select minimum margin cut factor for Markdown",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.pricing_constraints.mkd_margin_perc_min",
      xs: 12,
      md: 6,
    },
    mkd_margin_perc_step_size: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set step size for markdown",
      label: "Select step size for Markdown",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.pricing_constraints.mkd_margin_perc_step_size",
      xs: 12,
      md: 6,
    },
    lqd_margin_perc_min: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set minimum margin cut factor for liquidation",
      label: "Select minimum margin cut factor for Liquidation",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.pricing_constraints.lqd_margin_perc_min",
      xs: 12,
      md: 6,
    },
    lqd_margin_perc_step_size: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set step size for liquidation",
      label: "Select step size for Liquidation",
      maxRange: 5000,
      minRange: 0,
      path: "scenario_plan.pricing_constraints.lqd_margin_perc_step_size",
      xs: 12,
      md: 6,
    },
    //New Pricing Constraints
    revenue_weight_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select revenue weight column",
      label: "Select Revenue Weight Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.revenue_weight_col",
      xs: 12,
      md: 6,
    },
    revenue_weight: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set revenue weight",
      label: "Set Revenue Weight",
      maxRange: 1000,
      minRange: -1000,
      path: "scenario_plan.pricing_constraints.revenue_weight",
      xs: 12,
      md: 6,
    },

    Min_Price_Change_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select minimum price change column",
      label: "Select Minimum Price Change Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.Min_Price_Change_col",
      xs: 12,
      md: 6,
    },
    Max_Price_Change_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select maximum price change column",
      label: "Select Maximum Price Change Column",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.Max_Price_Change_col",
      xs: 12,
      md: 6,
    },
    step_change_min_to_max: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set step change min to max",
      label: "Set Step Change Min to Max",
      maxRange: 1000,
      minRange: -1000,
      path: "scenario_plan.pricing_constraints.step_change_min_to_max",
      xs: 12,
      md: 6,
    },
    cuts_by_sales_buckets: {
      component: "AutoComplete",
      conflictCheck: false,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select cuts by sales buckets",
      label: "Select Cuts by sales buckets",
      isMultiSelect: true,
      values: [
        "5",
        "10",
        "15",
        "20",
        "25",
        "30",
        "35",
        "40",
        "45",
        "50",
        "55",
        "60",
        "65",
        "70",
        "75",
        "80",
        "85",
        "90",
        "95",
        "100",
      ],
      dateFormat: false,
      path: "scenario_plan.pricing_constraints.cuts_by_sales_buckets",
      xs: 12,
      md: 6,
    },
    current_discount_assumption: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set current discount assumption",
      label: "Set Current Discount Assumption",
      maxRange: 1000,
      minRange: -1000,
      path: "scenario_plan.pricing_constraints.current_discount_assumption",
      xs: 12,
      md: 6,
    },
    liquidation_multiplier: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set liquidation multiplier",
      label: "Set Liquidation Multiplier",
      maxRange: 1000,
      minRange: -1000,
      path: "scenario_plan.pricing_constraints.liquidation_multiplier",
      xs: 12,
      md: 6,
    },
    rounding_off_price: {
      component: "Check",
      target: "context",
      is_enabled: true,
      question: "Enable price rounding offs?",
      direction: "row",
      path: "scenario_plan.pricing_constraints.rounding_off_price",
      xs: 12,
      md: 6,
    },
    round_off_by_multiplication: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set round off by multiplication",
      label: "Set Round Off By Multiplication",
      maxRange: 1000,
      minRange: -1000,
      path: "scenario_plan.pricing_constraints.round_off_by_multiplication",
      xs: 12,
      md: 6,
    },
    round_off_by_addition: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set round off by addition",
      label: "Set Round Off By Addition",
      maxRange: 1000,
      minRange: -1000,
      path: "scenario_plan.pricing_constraints.round_off_by_addition",
      xs: 12,
      md: 6,
    },

    optimization_period: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set optimization history (Days)",
      label: "Optimization History (Days)",
      maxRange: 1000,
      minRange: -1000,
      path: "etl.optimization_period",
      xs: 12,
      md: 6,
    },
    optimization_forecast_period: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set optimization for (Days)",
      label: "Optimization For (Days)",
      maxRange: 1000,
      minRange: -1000,
      path: "etl.optimization_forecast_period",
      xs: 12,
      md: 6,
    },
    epsilon: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set optimization gap (epsilon)",
      label: "Optimization Gap (epsilon)",
      maxRange: 1000,
      minRange: -1000,
      path: "scenario_plan.epsilon",
      xs: 12,
      md: 6,
    },
    sku_id_col: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select pack size field",
      label: "Pack Size field (For Discrete Optimization)",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.sku_id_col",
      xs: 12,
      md: 6,
    },
    dead_stock_granularity: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select dead stock granularity",
      label: "Dead Stock Granularity",
      isMultiSelect: true,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.dead_stock_granularity",
      xs: 12,
      md: 6,
    },
    inventory_ageing_flag: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select inventory ageing flag",
      label: "Inventory Ageing Flag",
      isMultiSelect: false,
      values: "taggedColumns",
      dateFormat: false,
      path: "scenario_plan.inventory_constraints.inventory_ageing_flag",
      xs: 12,
      md: 6,
    },

    //   Title Here = "New Product Forecasting for Recent Launch Items"
    new_product_forecasting_heading_1: {
      component: "heading",
      title: "New Product Forecasting for Recent Launch Items",
      xs: 12,
      md: 12,
    },
    need_new_product_forecasting: {
      question: "Need new product forecasting?",
      component: "Check",
      target: "context",
      is_enabled: true,
      path: "stacking.NewProduct",
      direction: "column",
      xs: 12,
      md: 3,
    },

    new_product_days_cutoff: {
      label: "New Product Days Cutoff",
      component: "Counter",
      target: "context",
      placeholder: "Set your count",
      path: "stacking.NewProduct_DaysCutoff",
      showLabel: true,
      maxRange: 5000,
      minRange: 0,
      xs: 12,
      md: 4.5,
    },
    new_product_sale_days: {
      label: "New Product Sale Days",
      component: "Counter",
      target: "context",
      is_enabled: true,
      placeholder: "Set your count",
      path: "stacking.NewProduct_SaleDays",
      showLabel: true,
      maxRange: 5000,
      minRange: 0,
      xs: 12,
      md: 4.5,
    },

    data_generation_dimension_recents: {
      component: "AutoComplete",
      conflictCheck: true,
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select  dimensions for cross learning",
      label: "Cross Learning Dimensions Recent",
      isMultiSelect: true,
      values: "taggedColumns", // Assuming taggedColumns is defined elsewhere
      dateFormat: false,
      path: "stacking.data_generation_dimension_recents",
      xs: 12,
      md: 12,
    },

    new_product_forecasting_heading_2: {
      component: "heading",
      title: "New Product Forecasting for Pre Launch Items",
      xs: 12,
      md: 12,
    },

    new_prod_granularity: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select forecast granularity",
      label: "Forecast Granularity",
      isMultiSelect: true,
      values:
        "Script(return config?.etl?.loaded_datasets?.new_product?.[0]?.field_tags?.ts_id_columns ?? [];)", // Assuming taggedColumns is defined elsewhere
      dateFormat: false,
      path: "scenario_plan.new_product_forecasting.new_prod_granularity",
      xs: 12,
      md: 4,
    },

    data_generation_dimension: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select cross learning dimensions",
      label: "Cross Learning Dimensions",
      isMultiSelect: true,
      values:
        "Script(return config?.etl?.loaded_datasets?.new_product?.[0]?.field_tags?.dimensions ?? [];)", // Assuming taggedColumns is defined elsewhere
      dateFormat: false,
      path: "scenario_plan.new_product_forecasting.data_generation_dimension",
      xs: 12,
      md: 4,
    },

    days_to_be_generated: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select historical reference period",
      label: "Historical Reference Period",
      isMultiSelect: false,
      values: [30, 60, 90], // Options as mentioned in your comment
      dateFormat: false,
      path: "scenario_plan.new_product_forecasting.days_to_be_generated",
      xs: 12,
      md: 4,
    },
    production_plan_dimensions: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select production plan dimensions",
      label: "Production Plan Dimensions",
      isMultiSelect: true,
      values: [
        "Script(return config?.scenario_plan?.post_model_demand_pattern?.dimensions ?? [];)",
        "Minimum Order Quantity",
        "lead_time",
      ], // Options as mentioned in your comment
      dateFormat: false,
      path: "scenario_plan.production_plan.production_plan_dimensions",
      xs: 12,
      md: 6,
    },
    production_plan_metrics: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select production plan metrics",
      label: "Production Plan Metrics",
      isMultiSelect: true,
      values: [
        "Beginning Inventory",
        "ML Forecast",
        "Sales",
        "Reorder Plan",
        "Production Plan Add-on",
        "Safety Stock Days",
        "Days On Inventory",
        "End Inventory",
        "Forecast Overwrite",
        "Total Stock Transfer",
      ], // Options as mentioned in your comment
      dateFormat: false,
      path: "scenario_plan.production_plan.production_plan_metrics",
      xs: 12,
      md: 6,
    },
    capacity_constraint: {
      component: "AutoComplete",

      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select capacity constraint",
      label: "Capacity Constraint",
      isMultiSelect: false,
      values: "taggedColumns", // Options as mentioned in your comment
      dateFormat: false,
      path: "scenario_plan.production_plan.capacity_constraint",
      xs: 12,
      md: 12,
    },
    production_plan_historical_horizon: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your history days",
      label: "Historical Horizon",
      maxRange: 100,
      minRange: 0,
      path: "scenario_plan.production_plan.production_plan_historical_horizon",
      xs: 12,
      md: 6,
    },
    production_plan_avg_calc_horizon: {
      component: "Counter",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Set your average calculation horizon",
      label: "Average Calculation Horizon",
      maxRange: 100,
      minRange: 0,
      path: "scenario_plan.production_plan.production_plan_avg_calc_horizon",
      xs: 12,
      md: 6,
    },
    production_plan_forecast_final_calculation: {
      component: "AutoComplete",
      target: "context",
      is_enabled: true,
      showLabel: true,
      placeholder: "Select final forecast calculation",
      label: "Final Forecast Calculation",
      isMultiSelect: false,
      values: ["average_forecasts", "ffill"],
      dateFormat: false,
      path: "scenario_plan.production_plan.production_plan_forecast_final_calculation",
      xs: 12,
      md: 12,
    },
  };
};
